missed spelling of STAGED_TESTS_DIR in yaml and needed check for fail in valicate bash wrapper

diff --git a/ctests/scripts/validate.sh.in b/ctests/scripts/validate.sh.in
--- a/ctests/scripts/validate.sh.in
+++ b/ctests/scripts/validate.sh.in
@@ -19,11 +19,18 @@ PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${HOMEgfs}/sorc/wxflow/src"
 export PYTHONPATH
 
 YAML_FILE="${HOMEgfs}/ctests/cases/${TEST_NAME}.yaml"
-echo "validating '${TEST_NAME}' with yaml file '${INPUTS_YAML}'"
+echo "validating '${TEST_NAME}' with yaml file '${YAML_FILE}'"
 
 TEST_NAME="${TEST_NAME}" \
 RUNTESTS="${RUNTESTS}" \
 STAGED_TESTS_DIR="${STAGED_TESTS_DIR}" \
 "${HOMEgfs}/ctests/scripts/validate.py" --yaml "${YAML_FILE}"  --test_date "${TEST_DATE}"
+rc=$?
+if [[ "${rc}" -ne 0 ]]; then
+    set +x
+    echo "Failed to validate for '${TEST_NAME}' with '${YAML_FILE}'"
+    set -x
+    exit "${rc}"
+fi
 	
 exit 0
