Remove md5 checksum check, note issue with htar indexing

diff --git a/parm/globus/todo.sh.j2 b/parm/globus/todo.sh.j2
--- a/parm/globus/todo.sh.j2
+++ b/parm/globus/todo.sh.j2
@@ -13,38 +13,40 @@ file_full="${cwd}/${file}"
 mkdir -p "${log_directory}"
 
 log_file="${log_directory}/hpss_status_${globus_xfer_id}.log"
-touch "${log_file}"
+rm -f "${log_file}"
 
 send_to_hpss()
 {
-    # Check that the MD5 checksum matches what was sent
-    chk=$(md5sum "${file_full}")
-    if [[ "${chk}" != "${globus_xfer_id}  ${file_full}" ]]; then
-        echo "MD5 checksum of ${file} does not match.  Exiting." >> "${log_file}"
-        return 1
-    fi
-
     # Write a command file to place the file on hpss and protect it
     local hpss_target="${hpss_target_dir}/${file}"
     local command_file="command_file_${globus_xfer_id}"
-    echo "mkdir -p ${hpss_dir}" >> "${command_file}"
+    echo "mkdir -p ${hpss_target_dir}" >> "${command_file}"
     echo "put ${file_full} :  ${hpss_target}" >> "${command_file}"
 
     hsi in "${command_file}" >> "${log_file}" 2>&1
     # shellcheck disable=SC2181
     if [[ $? != 0 ]]; then
         echo "Failed to send ${file} to HPSS." >> "${log_file}"
-        return 2
+        return 1
     fi
 
     rm -f "${command_file}"
 
     # Create an index file if the file is a tarball
     if [[ ${file} == *.tar ]]; then
-        if ! htar -Xvf "${hpss_target}" >> "${log_file}" 2>&1; then
-            echo "Failed to create an index file for ${hpss_target}.  Exiting." >> "${log_file}"
-            return 3
+        # For now, ignore errors coming from the index command.
+        # Issue RDHPCS#2025020754000121 opened with RDHPCS.
+        save_e=$-
+        set +e
+        htar -Xvf "${hpss_target}" > /dev/null 2>&1
+        if [[ "${save_e}" =~ e ]]; then
+            set -e
         fi
+        # TODO Reinstate error checking and logging when creating index files
+        #if ! htar -Xvf "${hpss_target}" >> "${log_file}" 2>&1; then
+            #echo "Failed to create an index file for ${hpss_target}.  Exiting." >> "${log_file}"
+            #return 2
+        #fi
     fi
 
     return 0
