removed references to rocotojobcard in CTest executatale bash template.  CTest exists when path to Rocoto is not specified because it requires the feature branched Rocoto

diff --git a/dev/ctests/scripts/execute.sh.in b/dev/ctests/scripts/execute.sh.in
--- a/dev/ctests/scripts/execute.sh.in
+++ b/dev/ctests/scripts/execute.sh.in
@@ -8,7 +8,6 @@ TEST_NAME=$("${HOMEgfs}/dev/ci/scripts/utils/ci_utils.sh" get_pslot "@CMAKE_CURR
 JOB=${2:?"Job name is required"}
 idate=$3
 
-# Use standard rocotoboot with --dryrun flag
 CASEDIR="@CMAKE_CURRENT_BINARY_DIR@/RUNTESTS/EXPDIR/${TEST_NAME}"
 cd "${CASEDIR}"
 rm -f ./*.db
@@ -20,13 +19,13 @@ rm -f ./jobcard
 source "${HOMEgfs}/ush/detect_machine.sh"
 source "${HOMEgfs}/dev/ci/platforms/config.${MACHINE_ID}"
 
-if [[ -x "${GFS_CI_ROCOTO_PATH}/rocotojobcard" ]]; then
-    echo "Using Rocoto GFS Utility rocotojobcard to create job card."
-    "${GFS_CI_ROCOTO_PATH}/rocotojobcard" -w "${TEST_NAME}.xml" -v 10 -c "${idate}00" -t "${JOB}" > "${TEST_NAME}.sub" || true
-else
+if [[ -x "${GFS_CI_ROCOTO_PATH}/rocotoboot" ]]; then
     yes | "${GFS_CI_ROCOTO_PATH}/rocotoboot" --dryrun -d "${TEST_NAME}.db" -w "${TEST_NAME}.xml" -v 10 -c "${idate}00" -t "${JOB}" 2> jobcard || true
     # Rocoto outputs the job card inside of {{}}.  Strip all other output to get just the job card.
     sed -n '/^{{/,/^}}/p' < jobcard | sed '1d;$d'  > "${TEST_NAME}.sub" || true
+else
+    echo "ERROR: Custom Rocoto build with dryrun feature not found at ${GFS_CI_ROCOTO_PATH}."
+    exit 1
 fi
 
 #TODO - Generalize for batch system (hard coded to slurm)
