gh should authenticate automaticly with GITHUB_TOKEN beng set, using it with echo fails because it is protected

diff --git a/dev/ci/gitlab-ci-badges.yml b/dev/ci/gitlab-ci-badges.yml
--- a/dev/ci/gitlab-ci-badges.yml
+++ b/dev/ci/gitlab-ci-badges.yml
@@ -41,9 +41,16 @@ update_status_badges:
       chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
       apt-get update -qq && apt-get install -y -qq gh
-      
-      # Authenticate GitHub CLI
-      echo "$GITHUB_TOKEN" | gh auth login --with-token
+      echo "GitHub CLI installed successfully."
+
+      # Check for authenticate with GitHub CLI using the
+      # provided token GITHUB_TOKEN from GitLab CI/CD variables
+      gh auth login status
+      if [ $? -ne 0 ]; then
+        echo "Authenticating with GitHub CLI failed"
+      else
+        echo "Already authenticated with GitHub CLI."
+      fi
       
       # Create directory for badge files
       mkdir -p badges
