Update jobs/JGCDAS_ATMOS_INITIALIZE
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/jobs/JGCDAS_ATMOS_INITIALIZE b/jobs/JGCDAS_ATMOS_INITIALIZE
--- a/jobs/JGCDAS_ATMOS_INITIALIZE
+++ b/jobs/JGCDAS_ATMOS_INITIALIZE
@@ -48,8 +48,8 @@ fi
 # Remove the Temporary working directory
 ##########################################
 cd "${DATAROOT}" || (
-    echo "${DATAROOT} does not exist. ABORT!"
-    exit 1
+  echo "${DATAROOT} does not exist. ABORT!"
+  exit 1
 )
 if [[ "${KEEPDATA}" == "NO" ]]; then
     rm -rf "${DATA}"
