Linter done for two J-jobs before lunch

diff --git a/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE b/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE
--- a/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE
+++ b/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE
@@ -1,26 +1,26 @@
 #!/bin/bash
 export STRICT="NO"
-source "$HOMEgfs/ush/preamble.sh"
+source "${HOMEgfs}/ush/preamble.sh"
 
 #############################
 # Source relevant config files
 #############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
 configs="base aeroanl aeroanlfinal"
-config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
-for config in $configs; do
-    . $config_path/config.$config
+config_path=${EXPDIR:-${NWROOT}/gfs.${gfs_ver}/parm/config}
+for config in ${configs}; do
+    . "${config_path}/config.${config}"
     status=$?
-    [[ $status -ne 0 ]] && exit $status
+    [[ ${status} -ne 0 ]] && exit "${status}"
 done
 
 
 ##########################################
 # Source machine runtime environment
 ##########################################
-. $HOMEgfs/env/${machine}.env aeroanlfinal
+. "${HOMEgfs}/env/${machine}.env" aeroanlfinal
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit "${status}"
 
 
 ##############################################
@@ -43,11 +43,11 @@ export COMPONENT=${COMPONENT:-chem}
 # Obtain unique process id (pid) and make temp directory
 ##############################################
 export pid=${pid:-$$}
-export outid=${outid:-"LL$job"}
+export outid=${outid:-"LL${job}"}
 
 export DATA=${DATA:-${DATAROOT}/aeroanl_${CDATE}}
-mkdir -p $DATA
-cd $DATA || (echo "$DATA does not exist. ABORT!"; exit 1)
+mkdir -p "${DATA}"
+cd "${DATA}" || (echo "${DATA} does not exist. ABORT!"; exit 1)
 
 
 ##############################################
@@ -61,7 +61,8 @@ export pgmerr=errfile
 # Begin JOB SPECIFIC work
 ##############################################
 
-export GDATE=$(date +%Y%m%d%H -d "${CDATE:0:8} ${CDATE:8:2} - ${assim_freq} hours")
+GDATE=$(date +%Y%m%d%H -d "${CDATE:0:8} ${CDATE:8:2} - ${assim_freq} hours")
+export GDATE
 gPDY=${GDATE:0:8}
 export gcyc=${GDATE:8:2}
 export GDUMP=${GDUMP:-"gdas"}
@@ -69,16 +70,16 @@ export GDUMP=${GDUMP:-"gdas"}
 export OPREFIX="${CDUMP}.t${cyc}z."
 export GPREFIX="${GDUMP}.t${gcyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
-export GSUFFIX=${GSUFFIX:-$SUFFIX}
-export ASUFFIX=${ASUFFIX:-$SUFFIX}
+export GSUFFIX=${GSUFFIX:-${SUFFIX}}
+export ASUFFIX=${ASUFFIX:-${SUFFIX}}
 
-export COMOUT=${COMOUT:-$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT}
+export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
 
-mkdir -p $COMOUT
+mkdir -p "${COMOUT}"
 
 # COMIN_GES and COMIN_GES_ENS are used in script
-export COMIN_GES="$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
-export COMIN_GES_ENS="$ROTDIR/enkf$GDUMP.$gPDY/$gcyc/$COMPONENT"
+export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_GES_ENS="${ROTDIR}/enkf${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
 
 # NOTE BELOW IS A HACK FOR TESTING
 # PLEASE FIX THIS LATER
@@ -86,17 +87,17 @@ export COMIN_GES_ENS="$ROTDIR/enkf$GDUMP.$gPDY/$gcyc/$COMPONENT"
 # HOW TO HANDLE DIFFERENT COMPILERS/ETC. FOR MODEL VS DA
 # PROD_UTIL, ETC. DO NOT EXIST FOR JEDI MODULE VERSIONS
 module purge
-module use $HOMEgfs/sorc/gdas.cd/modulefiles
-machinelower=$(echo "$machine" | awk '{print tolower($0)}')
-module load GDAS/$machinelower
+module use "${HOMEgfs}/sorc/gdas.cd/modulefiles"
+machinelower=$(echo "${machine}" | awk '{print tolower($0)}')
+module load "GDAS/${machinelower}"
 
 ###############################################################
 # Run relevant script
 
-EXSCRIPT=${GDASAEROFINALPY:-$HOMEgfs/scripts/exgdas_global_aero_analysis_finalize.py}
-$EXSCRIPT
+EXSCRIPT=${GDASAEROFINALPY:-${HOMEgfs}/scripts/exgdas_global_aero_analysis_finalize.py}
+${EXSCRIPT}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit "${status}"
 
 ##############################################
 # End JOB SPECIFIC work
@@ -105,14 +106,14 @@ status=$?
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [[ -e "${pgmout}" ]] ; then
+  cat "${pgmout}"
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
-[[ $KEEPDATA = "NO" ]] && rm -rf $DATA
+cd "${DATAROOT}" || exit 1
+[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"
 
 exit 0
