run shellcheck with SC2250 on these scripts

diff --git a/jobs/JGDAS_ENKF_FCST b/jobs/JGDAS_ENKF_FCST
--- a/jobs/JGDAS_ENKF_FCST
+++ b/jobs/JGDAS_ENKF_FCST
@@ -1,13 +1,13 @@
 #! /usr/bin/env bash
 
-source "$HOMEgfs/ush/preamble.sh"
+source "${HOMEgfs}/ush/preamble.sh"
 
 ##############################################
 # make temp directory
 ##############################################
 export DATA=${DATA:-${DATAROOT}/${jobid}}
-mkdir -p $DATA
-cd $DATA
+mkdir -p ${DATA}
+cd ${DATA}
 
 
 ##############################################
@@ -29,22 +29,22 @@ export pgmerr=errfile
 #############################
 # Source relevant config files
 #############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
-config_path=${EXPDIR:-$PACKAGEROOT/gfs.${gfs_ver}/parm/config}
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
+config_path=${EXPDIR:-${PACKAGEROOT}/gfs.${gfs_ver}/parm/config}
 configs="base fcst efcs"
-for config in $configs; do
-    . $config_path/config.$config
+for config in ${configs}; do
+    . ${config_path}/config.${config}
     status=$?
-    [[ $status -ne 0 ]] && exit $status
+    [[ ${status} -ne 0 ]] && exit ${status}
 done
 
 
 ##########################################
 # Source machine runtime environment
 ##########################################
-. $HOMEgfs/env/${machine}.env efcs
+. ${HOMEgfs}/env/${machine}.env efcs
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -59,16 +59,16 @@ export rCDUMP="gdas"
 # Begin JOB SPECIFIC work
 ##############################################
 
-export CASE=$CASE_ENKF
+export CASE=${CASE_ENKF}
 
 # COMOUT is used in script
-export COMOUT="$ROTDIR/enkf$CDUMP.$PDY/$cyc/$COMPONENT"
+export COMOUT="${ROTDIR}/enkf${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
 
 
 # Forecast length for EnKF forecast
-export FHMIN=$FHMIN_ENKF
-export FHOUT=$FHOUT_ENKF
-export FHMAX=$FHMAX_ENKF
+export FHMIN=${FHMIN_ENKF}
+export FHOUT=${FHOUT_ENKF}
+export FHMAX=${FHMAX_ENKF}
 
 
 # Get ENSBEG/ENSEND from ENSGRP and NMEM_EFCSGRP
@@ -79,21 +79,21 @@ export ENSBEG=$((ENSEND - NMEM_EFCSGRP + 1))
 ###############################################################
 # Run relevant script
 
-${ENKFFCSTSH:-$SCRgfs/exgdas_enkf_fcst.sh}
+${ENKFFCSTSH:-${SCRgfs}/exgdas_enkf_fcst.sh}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 # Double check the status of members in ENSGRP
-EFCSGRP=$COMOUT/efcs.grp${ENSGRP}
+EFCSGRP=${COMOUT}/efcs.grp${ENSGRP}
 npass=0
-if [ -f $EFCSGRP ]; then
-    npass=$(grep "PASS" $EFCSGRP | wc -l)
+if [ -f ${EFCSGRP} ]; then
+    npass=$(grep "PASS" ${EFCSGRP} | wc -l)
 fi
-echo "$npass/$NMEM_EFCSGRP members successfull in efcs.grp$ENSGRP"
-if [ $npass -ne $NMEM_EFCSGRP ]; then
-    echo "FATAL ERROR: Failed members in group $ENSGRP, ABORT!"
-    cat $EFCSGRP
+echo "${npass}/${NMEM_EFCSGRP} members successfull in efcs.grp${ENSGRP}"
+if [ ${npass} -ne ${NMEM_EFCSGRP} ]; then
+    echo "FATAL ERROR: Failed members in group ${ENSGRP}, ABORT!"
+    cat ${EFCSGRP}
     exit 99
 fi
 
@@ -101,8 +101,8 @@ fi
 ##############################################
 # Send Alerts
 ##############################################
-if [ $SENDDBN = YES ] ; then
-   $DBNROOT/bin/dbn_alert MODEL ENKF1_MSC_fcsstat $job $EFCSGRP
+if [ ${SENDDBN} = YES ] ; then
+   ${DBNROOT}/bin/dbn_alert MODEL ENKF1_MSC_fcsstat ${job} ${EFCSGRP}
 fi
 
 
@@ -113,15 +113,15 @@ fi
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [ -e "${pgmout}" ] ; then
+  cat ${pgmout}
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
-[[ $KEEPDATA = "NO" ]] && rm -rf $DATA
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
 
 
 exit 0
diff --git a/jobs/JGDAS_ENKF_SELECT_OBS b/jobs/JGDAS_ENKF_SELECT_OBS
--- a/jobs/JGDAS_ENKF_SELECT_OBS
+++ b/jobs/JGDAS_ENKF_SELECT_OBS
@@ -1,13 +1,13 @@
 #! /usr/bin/env bash
 
-source "$HOMEgfs/ush/preamble.sh"
+source "${HOMEgfs}/ush/preamble.sh"
 
 ##############################################
 # make temp directory
 ##############################################
 export DATA=${DATA:-${DATAROOT}/${jobid}}
-mkdir -p $DATA
-cd $DATA
+mkdir -p ${DATA}
+cd ${DATA}
 
 
 ##############################################
@@ -29,22 +29,22 @@ export pgmerr=errfile
 #############################
 # Source relevant config files
 #############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
 configs="base anal eobs"
-config_path=${EXPDIR:-$PACKAGEROOT/gfs.${gfs_ver}/parm/config}
-for config in $configs; do
-    . $config_path/config.$config
+config_path=${EXPDIR:-${PACKAGEROOT}/gfs.${gfs_ver}/parm/config}
+for config in ${configs}; do
+    . ${config_path}/config.${config}
     status=$?
-    [[ $status -ne 0 ]] && exit $status
+    [[ ${status} -ne 0 ]] && exit ${status}
 done
 
 
 ##########################################
 # Source machine runtime environment
 ##########################################
-. $HOMEgfs/env/${machine}.env eobs
+. ${HOMEgfs}/env/${machine}.env eobs
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -61,13 +61,13 @@ export MAKE_ACFTBUFR=${MAKE_ACFTBUFR:-"NO"}
 # Begin JOB SPECIFIC work
 ##############################################
 
-GDATE=$($NDATE -$assim_freq $CDATE)
-gPDY=$(echo $GDATE | cut -c1-8)
-gcyc=$(echo $GDATE | cut -c9-10)
+GDATE=$(${NDATE} -${assim_freq} ${CDATE})
+gPDY=$(echo ${GDATE} | cut -c1-8)
+gcyc=$(echo ${GDATE} | cut -c9-10)
 GDUMP=${GDUMP:-"gdas"}
 
-export CASE=$CASE_ENKF
-export CDUMP_OBS=${CDUMP_OBS:-$CDUMP}
+export CASE=${CASE_ENKF}
+export CDUMP_OBS=${CDUMP_OBS:-${CDUMP}}
 
 export OPREFIX="${CDUMP_OBS}.t${cyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
@@ -75,47 +75,47 @@ export GPREFIX="${GDUMP}.t${gcyc}z."
 export GSUFFIX="${GSUFFIX:-".ensmean${SUFFIX}"}"
 export ASUFFIX="${ASUFFIX:-"${SUFFIX}"}"
 
-if [ $RUN_ENVIR = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
-    export COMIN_OBS=${COMIN_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_GES_OBS=${COMIN_GES_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/$GDUMP.$gPDY/$gcyc/$COMPONENT}
+if [ ${RUN_ENVIR} = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
+    export COMIN_OBS=${COMIN_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMIN_GES_OBS=${COMIN_GES_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}}
 else
-    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
+    export COMIN_OBS="${DMPDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
+    export COMIN_GES_OBS="${DMPDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
 fi
 
 # COMIN_GES, COMIN_ANL COMIN_GES_ENS, and COMOUT  are used in script
-COMIN_GES_CTL="$ROTDIR/gdas.$gPDY/$gcyc/$COMPONENT"
-export COMIN_ANL="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-export COMIN_GES_ENS="$ROTDIR/enkfgdas.$gPDY/$gcyc/$COMPONENT"
-export COMIN_GES=$COMIN_GES_ENS
-export COMOUT="$ROTDIR/enkf$CDUMP.$PDY/$cyc/$COMPONENT"
+COMIN_GES_CTL="${ROTDIR}/gdas.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_ANL="${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
+export COMIN_GES_ENS="${ROTDIR}/enkfgdas.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_GES=${COMIN_GES_ENS}
+export COMOUT="${ROTDIR}/enkf${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
 
 
-export ATMGES_ENSMEAN="$COMIN_GES_ENS/${GPREFIX}atmf006$GSUFFIX"
-if [ ! -f $ATMGES_ENSMEAN ]; then
-    echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = $ATMGES_ENSMEAN"
+export ATMGES_ENSMEAN="${COMIN_GES_ENS}/${GPREFIX}atmf006${GSUFFIX}"
+if [ ! -f ${ATMGES_ENSMEAN} ]; then
+    echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = ${ATMGES_ENSMEAN}"
     exit 1
 fi
 
-export LEVS=$($NCDUMP -h $ATMGES_ENSMEAN | grep -i "pfull" | head -1 | awk -F" = " '{print $2}' | awk -F" " '{print $1}') # get LEVS
+export LEVS=$(${NCDUMP} -h ${ATMGES_ENSMEAN} | grep -i "pfull" | head -1 | awk -F" = " '{print $2}' | awk -F" " '{print $1}') # get LEVS
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 # Link observational data
-export PREPQC="$COMIN_OBS/${OPREFIX}prepbufr"
-if [ ! -f $PREPQC ]; then
-    echo "WARNING: Global PREPBUFR FILE $PREPQC MISSING"
+export PREPQC="${COMIN_OBS}/${OPREFIX}prepbufr"
+if [ ! -f ${PREPQC} ]; then
+    echo "WARNING: Global PREPBUFR FILE ${PREPQC} MISSING"
 fi
-export TCVITL="$COMIN_ANL/${OPREFIX}syndata.tcvitals.tm00"
-if [[ $DONST = "YES" ]]; then
-   if [[ $MAKE_NSSTBUFR == "YES" ]]; then
+export TCVITL="${COMIN_ANL}/${OPREFIX}syndata.tcvitals.tm00"
+if [[ ${DONST} = "YES" ]]; then
+   if [[ ${MAKE_NSSTBUFR} == "YES" ]]; then
       export NSSTBF="${COMOUT}/${OPREFIX}nsstbufr"
    else
       export NSSTBF="${COMIN_OBS}/${OPREFIX}nsstbufr"
    fi
 fi
 
-if [[ $MAKE_ACFTBUFR == "YES" ]]; then
+if [[ ${MAKE_ACFTBUFR} == "YES" ]]; then
    export PREPQCPF="${COMOUT}/${OPREFIX}prepbufr.acft_profiles"
 else
    export PREPQCPF="${COMIN_OBS}/${OPREFIX}prepbufr.acft_profiles"
@@ -128,46 +128,46 @@ export GBIASAIR=${COMIN_GES_CTL}/${GPREFIX}abias_air
 export GRADSTAT=${COMIN_GES_CTL}/${GPREFIX}radstat
 
 # Bias correction coefficients related to ensemble mean
-export ABIAS="$COMOUT/${APREFIX}abias.ensmean"
-export ABIASPC="$COMOUT/${APREFIX}abias_pc.ensmean"
-export ABIASAIR="$COMOUT/${APREFIX}abias_air.ensmean"
-export ABIASe="$COMOUT/${APREFIX}abias_int.ensmean"
+export ABIAS="${COMOUT}/${APREFIX}abias.ensmean"
+export ABIASPC="${COMOUT}/${APREFIX}abias_pc.ensmean"
+export ABIASAIR="${COMOUT}/${APREFIX}abias_air.ensmean"
+export ABIASe="${COMOUT}/${APREFIX}abias_int.ensmean"
 
 # Diagnostics related to ensemble mean
-export GSISTAT="$COMOUT/${APREFIX}gsistat.ensmean"
-export CNVSTAT="$COMOUT/${APREFIX}cnvstat.ensmean"
-export OZNSTAT="$COMOUT/${APREFIX}oznstat.ensmean"
-export RADSTAT="$COMOUT/${APREFIX}radstat.ensmean"
+export GSISTAT="${COMOUT}/${APREFIX}gsistat.ensmean"
+export CNVSTAT="${COMOUT}/${APREFIX}cnvstat.ensmean"
+export OZNSTAT="${COMOUT}/${APREFIX}oznstat.ensmean"
+export RADSTAT="${COMOUT}/${APREFIX}radstat.ensmean"
 
 # Select observations based on ensemble mean
 export RUN_SELECT="YES"
 export USE_SELECT="NO"
-export SELECT_OBS="$COMOUT/${APREFIX}obsinput.ensmean"
+export SELECT_OBS="${COMOUT}/${APREFIX}obsinput.ensmean"
 
 export DIAG_SUFFIX="_ensmean"
 
 # GSI namelist options specific to eobs
-export SETUP_INVOBS="passive_bc=.false.,$SETUP_INVOBS"
+export SETUP_INVOBS="passive_bc=.false.,${SETUP_INVOBS}"
 
 # Ensure clean stat tarballs for ensemble mean
-for fstat in $CNVSTAT $OZNSTAT $RADSTAT; do
-    [[ -f $fstat ]] && rm -f $fstat
+for fstat in ${CNVSTAT} ${OZNSTAT} ${RADSTAT}; do
+    [[ -f ${fstat} ]] && rm -f ${fstat}
 done
 
 
 ###############################################################
 # Run relevant script
 
-${INVOBSSH:-$SCRgfs/exgdas_enkf_select_obs.sh}
+${INVOBSSH:-${SCRgfs}/exgdas_enkf_select_obs.sh}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
 # Send Alerts
 ##############################################
-if [ $SENDDBN = YES ] ; then
-   $DBNROOT/bin/dbn_alert MODEL ENKF1_MSC_gsistat $job $GSISTAT
+if [ ${SENDDBN} = YES ] ; then
+   ${DBNROOT}/bin/dbn_alert MODEL ENKF1_MSC_gsistat ${job} ${GSISTAT}
 fi
 
 
@@ -178,15 +178,15 @@ fi
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [ -e "${pgmout}" ] ; then
+  cat ${pgmout}
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
-[[ $KEEPDATA = "NO" ]] && rm -rf $DATA
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
 
 
 exit 0
diff --git a/jobs/JGDAS_GLOBAL_ATMOS_ANALYSIS_PREP b/jobs/JGDAS_GLOBAL_ATMOS_ANALYSIS_PREP
--- a/jobs/JGDAS_GLOBAL_ATMOS_ANALYSIS_PREP
+++ b/jobs/JGDAS_GLOBAL_ATMOS_ANALYSIS_PREP
@@ -1,13 +1,13 @@
 #!/bin/bash
 
-source "$HOMEgfs/ush/preamble.sh"
+source "${HOMEgfs}/ush/preamble.sh"
 
 ##############################################
 # make temp directory
 ##############################################
 export DATA=${DATA:-${DATAROOT}/${jobid}}
-mkdir -p $DATA
-cd $DATA || (echo "$DATA does not exist. ABORT!"; exit 1)
+mkdir -p ${DATA}
+cd ${DATA} || (echo "${DATA} does not exist. ABORT!"; exit 1)
 
 
 ##############################################
@@ -29,22 +29,22 @@ export pgmerr=errfile
 #############################
 # Source relevant config files
 #############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
-config_path=${EXPDIR:-$PACKAGEROOT/gfs.${gfs_ver}/parm/config}
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
+config_path=${EXPDIR:-${PACKAGEROOT}/gfs.${gfs_ver}/parm/config}
 configs="base atmanal atmanalprep"
-for config in $configs; do
-    . $config_path/config.$config
+for config in ${configs}; do
+    . ${config_path}/config.${config}
     status=$?
-    [[ $status -ne 0 ]] && exit $status
+    [[ ${status} -ne 0 ]] && exit ${status}
 done
 
 
 ##########################################
 # Source machine runtime environment
 ##########################################
-. $HOMEgfs/env/${machine}.env atmanalprep
+. ${HOMEgfs}/env/${machine}.env atmanalprep
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -66,26 +66,26 @@ export GDUMP=${GDUMP:-"gdas"}
 export OPREFIX="${CDUMP}.t${cyc}z."
 export GPREFIX="${GDUMP}.t${gcyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
-export GSUFFIX=${GSUFFIX:-$SUFFIX}
-export ASUFFIX=${ASUFFIX:-$SUFFIX}
+export GSUFFIX=${GSUFFIX:-${SUFFIX}}
+export ASUFFIX=${ASUFFIX:-${SUFFIX}}
 
-export COMOUT=${COMOUT:-$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT}
+export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
 
-mkdir -p $COMOUT
+mkdir -p ${COMOUT}
 
 # COMIN_GES and COMIN_GES_ENS are used in script
-export COMIN_GES="$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
-export COMIN_GES_ENS="$ROTDIR/enkf$GDUMP.$gPDY/$gcyc/$COMPONENT"
+export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_GES_ENS="${ROTDIR}/enkf${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
 
 # Add UFSDA to PYTHONPATH
-export PYTHONPATH=$HOMEgfs/sorc/gdas.cd/ush/:$PYTHONPATH
+export PYTHONPATH=${HOMEgfs}/sorc/gdas.cd/ush/:${PYTHONPATH}
 
 ###############################################################
 # Run relevant script
-EXSCRIPT=${GDASPREPPY:-$HOMEgfs/scripts/exgdas_global_atmos_analysis_prep.py}
-$EXSCRIPT
+EXSCRIPT=${GDASPREPPY:-${HOMEgfs}/scripts/exgdas_global_atmos_analysis_prep.py}
+${EXSCRIPT}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 ##############################################
 # End JOB SPECIFIC work
@@ -94,14 +94,14 @@ status=$?
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [ -e "${pgmout}" ] ; then
+  cat ${pgmout}
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
-[[ $KEEPDATA = "NO" ]] && rm -rf $DATA
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
 
 exit 0
diff --git a/jobs/JGLOBAL_ATMOS_SFCANL b/jobs/JGLOBAL_ATMOS_SFCANL
--- a/jobs/JGLOBAL_ATMOS_SFCANL
+++ b/jobs/JGLOBAL_ATMOS_SFCANL
@@ -1,13 +1,13 @@
 #! /usr/bin/env bash
 
-source "$HOMEgfs/ush/preamble.sh"
+source "${HOMEgfs}/ush/preamble.sh"
 
 ##############################################
 # Obtain unique process id (pid) and make temp directory
 ##############################################
 export DATA=${DATA:-${DATAROOT}/${jobid}}
-mkdir -p $DATA
-cd $DATA
+mkdir -p ${DATA}
+cd ${DATA}
 
 
 ##############################################
@@ -29,21 +29,21 @@ export pgmerr=errfile
 #############################
 # Source relevant config files
 #############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
 configs="base sfcanl"
-config_path=${EXPDIR:-$PACKAGEROOT/gfs.${gfs_ver}/parm/config}
-for config in $configs; do
-    . $config_path/config.$config
+config_path=${EXPDIR:-${PACKAGEROOT}/gfs.${gfs_ver}/parm/config}
+for config in ${configs}; do
+    . ${config_path}/config.${config}
     status=$?
-    [[ $status -ne 0 ]] && exit $status
+    [[ ${status} -ne 0 ]] && exit ${status}
 done
 
 ##########################################
 # Source machine runtime environment
 ##########################################
-. $HOMEgfs/env/${machine}.env sfcanl
+. ${HOMEgfs}/env/${machine}.env sfcanl
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -52,8 +52,8 @@ status=$?
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
 export COMPONENT="atmos"
-if [ $RUN_ENVIR = "nco" ]; then
-    export ROTDIR=${COMROOT:?}/$NET/$envir
+if [ ${RUN_ENVIR} = "nco" ]; then
+    export ROTDIR=${COMROOT:?}/${NET}/${envir}
 fi
 
 
@@ -61,37 +61,37 @@ fi
 # Begin JOB SPECIFIC work
 ##############################################
 
-GDATE=$($NDATE -$assim_freq $CDATE)
-gPDY=$(echo $GDATE | cut -c1-8)
-gcyc=$(echo $GDATE | cut -c9-10)
+GDATE=$(${NDATE} -${assim_freq} ${CDATE})
+gPDY=$(echo ${GDATE} | cut -c1-8)
+gcyc=$(echo ${GDATE} | cut -c9-10)
 GDUMP=${GDUMP:-"gdas"}
 
 export OPREFIX="${CDUMP}.t${cyc}z."
 export GPREFIX="${GDUMP}.t${gcyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
-export GSUFFIX=${GSUFFIX:-$SUFFIX}
-export ASUFFIX=${ASUFFIX:-$SUFFIX}
+export GSUFFIX=${GSUFFIX:-${SUFFIX}}
+export ASUFFIX=${ASUFFIX:-${SUFFIX}}
 
 
-if [ $RUN_ENVIR = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
-    export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_OBS=${COMIN_OBS:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_GES_OBS=${COMIN_GES_OBS:-$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT}
+if [ ${RUN_ENVIR} = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
+    export COMIN=${COMIN:-${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMOUT=${COMOUT:-${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMIN_OBS=${COMIN_OBS:-${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMIN_GES_OBS=${COMIN_GES_OBS:-${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}}
 else
-    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-    export COMIN_OBS="$DMPDIR/$CDATE/$CDUMP"
-    export COMIN_GES_OBS="$DMPDIR/$GDATE/$GDUMP"
+    export COMOUT="${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
+    export COMIN_OBS="${DMPDIR}/${CDATE}/${CDUMP}"
+    export COMIN_GES_OBS="${DMPDIR}/${GDATE}/${GDUMP}"
 fi
-mkdir -m 775 -p $COMOUT
+mkdir -m 775 -p ${COMOUT}
 # COMIN_GES and COMIN_GES_ENS are used in script
-export COMIN_GES="$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
-export COMIN_GES_ENS="$ROTDIR/enkfgdas.$gPDY/$gcyc/$COMPONENT"
+export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_GES_ENS="${ROTDIR}/enkfgdas.${gPDY}/${gcyc}/${COMPONENT}"
 
 
-export ATMGES="$COMIN_GES/${GPREFIX}atmf006${GSUFFIX}"
-if [ ! -f $ATMGES ]; then
-    echo "FATAL ERROR: FILE MISSING: ATMGES = $ATMGES"
+export ATMGES="${COMIN_GES}/${GPREFIX}atmf006${GSUFFIX}"
+if [ ! -f ${ATMGES} ]; then
+    echo "FATAL ERROR: FILE MISSING: ATMGES = ${ATMGES}"
     exit 1
 fi
 
@@ -99,9 +99,9 @@ fi
 ###############################################################
 # Run relevant script
 
-${SFCANALSH:-$SCRgfs/exglobal_atmos_sfcanl.sh}
+${SFCANALSH:-${SCRgfs}/exglobal_atmos_sfcanl.sh}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -111,15 +111,15 @@ status=$?
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [ -e "${pgmout}" ] ; then
+  cat ${pgmout}
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
-[[ $KEEPDATA = "NO" ]] && rm -rf $DATA
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
 
 
 exit 0
