Make all aeroanl jobs use same data dir

diff --git a/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_INITIALIZE b/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_INITIALIZE
--- a/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_INITIALIZE
+++ b/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_INITIALIZE
@@ -24,17 +24,6 @@ status=$?
 
 
 ##############################################
-# Obtain unique process id (pid) and make temp directory
-##############################################
-export pid=${pid:-$$}
-export outid=${outid:-"LL$job"}
-
-export DATA=${DATA:-${DATAROOT}/${jobid:?}}
-mkdir -p $DATA
-cd $DATA || (echo "$DATA does not exist. ABORT!"; exit 1)
-
-
-##############################################
 # Run setpdy and initialize PDY variables
 ##############################################
 export cycle="t${cyc}z"
@@ -43,18 +32,30 @@ setpdy.sh
 
 
 ##############################################
-# Determine Job Output Name on System
-##############################################
-export pgmout="OUTPUT.${pid}"
-export pgmerr=errfile
-
-
-##############################################
 # Set variables used in the script
 ##############################################
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
 export COMPONENT=${COMPONENT:-chem}
+
+
+##############################################
+# Obtain unique process id (pid) and make temp directory
+##############################################
+export pid=${pid:-$$}
+export outid=${outid:-"LL$job"}
+
+export DATA=${DATA:-${DATAROOT}/aeroanl_${CDATE}}
+mkdir -p $DATA
+cd $DATA || (echo "$DATA does not exist. ABORT!"; exit 1)
+
+
+##############################################
+# Determine Job Output Name on System
+##############################################
+export pgmout="OUTPUT.${pid}"
+export pgmerr=errfile
+
 
 ##############################################
 # Begin JOB SPECIFIC work
