Change j-jobs

diff --git a/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE b/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE
--- a/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE
+++ b/jobs/JGDAS_GLOBAL_AERO_ANALYSIS_FINALIZE
@@ -1,15 +1,38 @@
-#!/bin/bash
+#! /usr/bin/env bash
+
 export STRICT="NO"
 source "${HOMEgfs}/ush/preamble.sh"
+
+##############################################
+# Enter temp directory
+##############################################
+export DATA=${DATA:-${DATAROOT}/aeroanl_${cyc}}
+cd "${DATA}" || (echo "${DATA} does not exist. ABORT!"; exit 1)
+
+
+##############################################
+# Run setpdy and initialize PDY variables
+##############################################
+export cycle="t${cyc}z"
+setpdy.sh
+. ./PDY
+
+
+##############################################
+# Determine Job Output Name on System
+##############################################
+export pid=${pid:-$$}
+export pgmout="OUTPUT.${pid}"
+export pgmerr=errfile
+
 
 #############################
 # Source relevant config files
 #############################
 export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
 configs="base aeroanl aeroanlfinal"
-config_path=${EXPDIR:-${NWROOT}/gfs.${gfs_ver}/parm/config}
 for config in ${configs}; do
-    . "${config_path}/config.${config}"
+    . "${EXPDIR}/config.${config}"
     status=$?
     [[ ${status} -ne 0 ]] && exit "${status}"
 done
@@ -24,36 +47,11 @@ status=$?
 
 
 ##############################################
-# Run setpdy and initialize PDY variables
-##############################################
-export cycle="t${cyc}z"
-setpdy.sh
-. ./PDY
-
-
-##############################################
 # Set variables used in the script
 ##############################################
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
 export COMPONENT="chem"
-
-
-##############################################
-# Obtain unique process id (pid) and make temp directory
-##############################################
-export pid=${pid:-$$}
-export outid=${outid:-"LL${job}"}
-
-export DATA=${DATA:-${DATAROOT}/aeroanl_${cyc}}
-cd "${DATA}" || (echo "${DATA} does not exist. ABORT!"; exit 1)
-
-
-##############################################
-# Determine Job Output Name on System
-##############################################
-export pgmout="OUTPUT.${pid}"
-export pgmerr=errfile
 
 
 ##############################################
