Update anl diag for COM refactor
Updates the analysis diagnostic jobs to use the new COM templates.

Refs: #761

diff --git a/jobs/JGDAS_ATMOS_ANALYSIS_DIAG b/jobs/JGDAS_ATMOS_ANALYSIS_DIAG
--- a/jobs/JGDAS_ATMOS_ANALYSIS_DIAG
+++ b/jobs/JGDAS_ATMOS_ANALYSIS_DIAG
@@ -7,8 +7,7 @@ source "${HOMEgfs}/ush/jjob_header.sh" -e "anal" -c "base anal analdiag"
 ##############################################
 # Set variables used in the script
 ##############################################
-export CDATE=${CDATE:-${PDY}${cyc}}
-export CDUMP=${CDUMP:-${RUN:-"gfs"}}
+export CDUMP="${RUN/enkf}"
 export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}
 
 
@@ -16,50 +15,44 @@ export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}
 # Begin JOB SPECIFIC work
 ##############################################
 
-GDATE=$(${NDATE} -${assim_freq} ${CDATE})
-gPDY=$(echo ${GDATE} | cut -c1-8)
-gcyc=$(echo ${GDATE} | cut -c9-10)
-GDUMP=${GDUMP:-"gdas"}
+DATE_PREV=$(${NDATE} -${assim_freq} ${CDATE})
+export PDY_PREV=${DATE_PREV:0:8}
+export cyc_PREV=${DATE_PREV:8:2}
+export GDUMP="gdas"
+export GDUMP_ENS="enkf${GDUMP}"
 
 export OPREFIX="${CDUMP}.t${cyc}z."
-export GPREFIX="${GDUMP}.t${gcyc}z."
-export APREFIX="${CDUMP}.t${cyc}z."
-export GPREFIX_ENS="enkf${GDUMP}.t${gcyc}z."
+export GPREFIX="${GDUMP}.t${cyc_PREV}z."
+export APREFIX="${RUN}.t${cyc}z."
+# export GPREFIX_ENS="${GDUMP_ENS}.t${cyc_PREV}z."
 
-declare -rx COMIN=${COM_ATMOS_ANALYSIS}
-declare -rx COMOUT=${COM_ATMOS_ANALYSIS}
-export DMPDIR=${DMPDIR:-$(compath.py "${envir}/obsproc/${obsproc_ver}")}
-COM_OBS=$(echo "${COM_OBS_TMPL}" | envsubst)
-COMIN_GES_OBS=$( {
-    RUN=${GDUMP}
-    PDY=${gPDY}
-    cyc=${gcyc}
-    echo "${COM_OBS_TMPL}" | envsubst
-})
+YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_ANALYSIS
 
-declare -rx COM_OBS
-declare -rx COMIN_GES_OBS
+# RUN=${GDUMP} YMD=${PDY} HH=${cyc} generate -rx \
+#     COM_OBS_PREV:COM_OBS_TMPL \
+#     COM_ATMOS_ANALYSIS_PREV:COM_ATMOS_ANALYSIS_TMPL
 
-mkdir -m 775 -p ${COMOUT}
-# COMIN_GES and COMIN_GES_ENS are used in script
-export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/atmos"
-export COMIN_GES_ENS="${ROTDIR}/enkfgdas.${gPDY}/${gcyc}"
+# MEMDIR='ensstat' RUN=${GDUMP} YMD=${PDY_PREV} HH=${cyc_PREV} generate_com -rx \
+#     COM_ATMOS_HISTORY_ENS_PREV:COM_ATMOS_HISTORY_TMPL
 
 
-export ATMGES="${COMIN_GES}/${GPREFIX}atmf006.nc"
-if [ ! -f ${ATMGES} ]; then
-    echo "FATAL ERROR: FILE MISSING: ATMGES = ${ATMGES}"
-    exit 1
-fi
+mkdir -m 775 -p ${COM_ATMOS_ANALYSIS}
 
 
-if [ ${DOHYBVAR} = "YES" ]; then
-    export ATMGES_ENSMEAN="${COMIN_GES_ENS}/${GPREFIX_ENS}atmf006.ensmean.nc"
-    if [ ! -f ${ATMGES_ENSMEAN} ]; then
-        echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = ${ATMGES_ENSMEAN}"
-        exit 2
-    fi
-fi
+# export ATMGES="${COMIN_GES}/${GPREFIX}atmf006.nc"
+# if [ ! -f ${ATMGES} ]; then
+#     echo "FATAL ERROR: FILE MISSING: ATMGES = ${ATMGES}"
+#     exit 1
+# fi
+
+
+# if [ ${DOHYBVAR} = "YES" ]; then
+#     export ATMGES_ENSMEAN="${COM_ATMOS_HISTORY_ENS_PREV}/${GPREFIX_ENS}atmf006.ensmean.nc"
+#     if [ ! -f ${ATMGES_ENSMEAN} ]; then
+#         echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = ${ATMGES_ENSMEAN}"
+#         exit 2
+#     fi
+# fi
 
 
 ###############################################################
