First step towards making j-jobs consistent in use from ecflow and rocoto (#1120)
Several jobs run in development mode do not adhere to EE2 standards.  Sometimes these development jobs do get used for operations at which time there is a rush in getting them to be standardized.
These jobs are also used to run parallel retrospectives and near-real time parallels.

This work is performed with GFSv17 and GEFSv13 as the target implementation.

This PR attempts to standardize the use of several variables as defined in the NCO EE2 standards document.
Specifically;
The following are defined in the job-card:
`DATAROOT`
`cyc`
`HOMEgfs`
`job`
`jobid=$job/$$` or `jobid=$PBS_JOBNAME/$PBS_JOBID` depending on Rocoto/Ops

The following are defined in the j-job:
`pid`
`DATA=DATAROOT/jobid`
`cycle`

This PR also fixes a bug in `exgfs_atmos_post.sh` that is only encountered when `WAFSF=YES` and in the `gdaspostanl` job.  An overzealous linter added extra white-space and put quotes around an argument for `wgrib2`.

diff --git a/jobs/JGDAS_GLOBAL_ATMOS_ENSANAL_PREP b/jobs/JGDAS_GLOBAL_ATMOS_ENSANAL_PREP
--- a/jobs/JGDAS_GLOBAL_ATMOS_ENSANAL_PREP
+++ b/jobs/JGDAS_GLOBAL_ATMOS_ENSANAL_PREP
@@ -1,37 +1,13 @@
 #!/bin/bash
 
-source "$HOMEgfs/ush/preamble.sh"
-
-#############################
-# Source relevant config files
-#############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
-configs="base atmensanal atmensanalprep"
-config_path=${EXPDIR:-$PACKAGEROOT/gfs.${gfs_ver}/parm/config}
-for config in $configs; do
-    . $config_path/config.$config
-    status=$?
-    [[ $status -ne 0 ]] && exit $status
-done
-
-
-##########################################
-# Source machine runtime environment
-##########################################
-. $HOMEgfs/env/${machine}.env atmensanalprep
-status=$?
-[[ $status -ne 0 ]] && exit $status
-
+source "${HOMEgfs}/ush/preamble.sh"
 
 ##############################################
-# Obtain unique process id (pid) and make temp directory
+# make temp directory
 ##############################################
-export pid=${pid:-$$}
-export outid=${outid:-"LL$job"}
-
-export DATA=${DATA:-${DATAROOT}/${jobid:?}}
-mkdir -p $DATA
-cd $DATA || (echo "$DATA does not exist. ABORT!"; exit 1)
+export DATA=${DATA:-${DATAROOT}/${jobid}}
+mkdir -p ${DATA}
+cd ${DATA} || (echo "${DATA} does not exist. ABORT!"; exit 1)
 
 
 ##############################################
@@ -45,8 +21,29 @@ setpdy.sh
 ##############################################
 # Determine Job Output Name on System
 ##############################################
+export pid=${pid:-$$}
 export pgmout="OUTPUT.${pid}"
 export pgmerr=errfile
+
+
+#############################
+# Source relevant config files
+#############################
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
+configs="base atmensanal atmensanalprep"
+for config in ${configs}; do
+    . ${EXPDIR}/config.${config}
+    status=$?
+    [[ ${status} -ne 0 ]] && exit ${status}
+done
+
+
+##########################################
+# Source machine runtime environment
+##########################################
+. ${HOMEgfs}/env/${machine}.env atmensanalprep
+status=$?
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -54,7 +51,7 @@ export pgmerr=errfile
 ##############################################
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
-export COMPONENT=${COMPONENT:-atmos}
+export COMPONENT="atmos"
 
 ##############################################
 # Begin JOB SPECIFIC work
@@ -68,30 +65,30 @@ export GDUMP=${GDUMP:-"gdas"}
 export OPREFIX="${CDUMP}.t${cyc}z."
 export GPREFIX="${GDUMP}.t${gcyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
-export GSUFFIX=${GSUFFIX:-$SUFFIX}
-export ASUFFIX=${ASUFFIX:-$SUFFIX}
+export GSUFFIX=${GSUFFIX:-${SUFFIX}}
+export ASUFFIX=${ASUFFIX:-${SUFFIX}}
 
-export COMOUT=${COMOUT:-$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT}
-export COMOUT_ENS=${COMOUT_ENS:-$ROTDIR/enkf$CDUMP.$PDY/$cyc/$COMPONENT}
+export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
+export COMOUT_ENS=${COMOUT_ENS:-${ROTDIR}/enkf${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
 
-mkdir -p $COMOUT
-mkdir -p $COMOUT_ENS
+mkdir -p ${COMOUT}
+mkdir -p ${COMOUT_ENS}
 
 # COMIN_GES and COMIN_GES_ENS are used in script
-export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-export COMIN_GES="$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
-export COMIN_GES_ENS="$ROTDIR/enkf$GDUMP.$gPDY/$gcyc/$COMPONENT"
+export COMIN="${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
+export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_GES_ENS="${ROTDIR}/enkf${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
 
 # Add UFSDA to PYTHONPATH
-export PYTHONPATH=$HOMEgfs/sorc/gdas.cd/ush/:$PYTHONPATH
+export PYTHONPATH=${HOMEgfs}/sorc/gdas.cd/ush/:${PYTHONPATH}
 
 ###############################################################
 # Run relevant script
 
-EXSCRIPT=${GDASPREPPY:-$HOMEgfs/scripts/exgdas_global_atmos_analysis_prep.py}
-$EXSCRIPT
+EXSCRIPT=${GDASPREPPY:-${HOMEgfs}/scripts/exgdas_global_atmos_analysis_prep.py}
+${EXSCRIPT}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 ##############################################
 # End JOB SPECIFIC work
@@ -100,14 +97,14 @@ status=$?
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [ -e "${pgmout}" ] ; then
+  cat ${pgmout}
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
-[[ $KEEPDATA = "NO" ]] && rm -rf $DATA
+cd ${DATAROOT}
+[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
 
 exit 0
diff --git a/jobs/JGLOBAL_ATMOS_ANALYSIS b/jobs/JGLOBAL_ATMOS_ANALYSIS
--- a/jobs/JGLOBAL_ATMOS_ANALYSIS
+++ b/jobs/JGLOBAL_ATMOS_ANALYSIS
@@ -1,39 +1,13 @@
 #! /usr/bin/env bash
 
-source "$HOMEgfs/ush/preamble.sh"
-
-export RUN_ENVIR=${RUN_ENVIR:-"nco"}
-
-#############################
-# Source relevant config files
-#############################
-export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
-configs="base anal"
-config_path=${EXPDIR:-$PACKAGEROOT/gfs.${gfs_ver}/parm/config}
-for config in $configs; do
-    . $config_path/config.$config
-    status=$?
-    [[ $status -ne 0 ]] && exit $status
-done
-
-
-##########################################
-# Source machine runtime environment
-##########################################
-. $HOMEgfs/env/${machine}.env anal
-status=$?
-[[ $status -ne 0 ]] && exit $status
-
+source "${HOMEgfs}/ush/preamble.sh"
 
 ##############################################
 # Obtain unique process id (pid) and make temp directory
 ##############################################
-export pid=${pid:-$$}
-export outid=${outid:-"LL$job"}
-
-export DATA=${DATA:-${DATAROOT}/${jobid:?}}
-mkdir -p $DATA
-cd $DATA
+export DATA=${DATA:-${DATAROOT}/${jobid}}
+mkdir -p ${DATA}
+cd ${DATA}
 
 
 ##############################################
@@ -47,8 +21,29 @@ setpdy.sh
 ##############################################
 # Determine Job Output Name on System
 ##############################################
+export pid=${pid:-$$}
 export pgmout="OUTPUT.${pid}"
 export pgmerr=errfile
+
+
+#############################
+# Source relevant config files
+#############################
+export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
+configs="base anal"
+for config in ${configs}; do
+    . ${EXPDIR}/config.${config}
+    status=$?
+    [[ ${status} -ne 0 ]] && exit ${status}
+done
+
+
+##########################################
+# Source machine runtime environment
+##########################################
+. ${HOMEgfs}/env/${machine}.env anal
+status=$?
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
@@ -56,8 +51,8 @@ export pgmerr=errfile
 ##############################################
 export CDATE=${CDATE:-${PDY}${cyc}}
 export CDUMP=${CDUMP:-${RUN:-"gfs"}}
-export COMPONENT=${COMPONENT:-atmos}
-export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"} 
+export COMPONENT="atmos"
+export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}
 export MAKE_NSSTBUFR=${MAKE_NSSTBUFR:-"NO"}
 export MAKE_ACFTBUFR=${MAKE_ACFTBUFR:-"NO"}
 
@@ -66,56 +61,56 @@ export MAKE_ACFTBUFR=${MAKE_ACFTBUFR:-"NO"}
 # Begin JOB SPECIFIC work
 ##############################################
 
-GDATE=$($NDATE -$assim_freq $CDATE)
-gPDY=$(echo $GDATE | cut -c1-8)
-gcyc=$(echo $GDATE | cut -c9-10)
+GDATE=$(${NDATE} -${assim_freq} ${CDATE})
+gPDY=$(echo ${GDATE} | cut -c1-8)
+gcyc=$(echo ${GDATE} | cut -c9-10)
 GDUMP=${GDUMP:-"gdas"}
 
 export OPREFIX="${CDUMP}.t${cyc}z."
 export GPREFIX="${GDUMP}.t${gcyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
-export GSUFFIX=${GSUFFIX:-$SUFFIX}
-export ASUFFIX=${ASUFFIX:-$SUFFIX}
+export GSUFFIX=${GSUFFIX:-${SUFFIX}}
+export ASUFFIX=${ASUFFIX:-${SUFFIX}}
 
 
-if [ $RUN_ENVIR = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
-    export COMIN=${COMIN:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMOUT=${COMOUT:-$ROTDIR/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_OBS=${COMIN_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/$RUN.$PDY/$cyc/$COMPONENT}
-    export COMIN_GES_OBS=${COMIN_GES_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/$GDUMP.$gPDY/$gcyc/$COMPONENT}
+if [ ${RUN_ENVIR} = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
+    export COMIN=${COMIN:-${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMOUT=${COMOUT:-${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMIN_OBS=${COMIN_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/${RUN}.${PDY}/${cyc}/${COMPONENT}}
+    export COMIN_GES_OBS=${COMIN_GES_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}}
 else
-    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-    export COMIN_OBS="$DMPDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
-    export COMIN_GES_OBS="$DMPDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
+    export COMOUT="${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
+    export COMIN_OBS="${DMPDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}"
+    export COMIN_GES_OBS="${DMPDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
 fi
-mkdir -m 775 -p $COMOUT
+mkdir -m 775 -p ${COMOUT}
 # COMIN_GES and COMIN_GES_ENS are used in script
-export COMIN_GES="$ROTDIR/$GDUMP.$gPDY/$gcyc/$COMPONENT"
-export COMIN_GES_ENS="$ROTDIR/enkfgdas.$gPDY/$gcyc/$COMPONENT"
+export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/${COMPONENT}"
+export COMIN_GES_ENS="${ROTDIR}/enkfgdas.${gPDY}/${gcyc}/${COMPONENT}"
 
 
-export ATMGES="$COMIN_GES/${GPREFIX}atmf006${GSUFFIX}"
-if [ ! -f $ATMGES ]; then
-    echo "FATAL ERROR: FILE MISSING: ATMGES = $ATMGES"
+export ATMGES="${COMIN_GES}/${GPREFIX}atmf006${GSUFFIX}"
+if [ ! -f ${ATMGES} ]; then
+    echo "FATAL ERROR: FILE MISSING: ATMGES = ${ATMGES}"
     exit 1
 fi
 
 
 # Get LEVS
 if [ ${GSUFFIX} = ".nc" ]; then
-    export LEVS=$($NCLEN $ATMGES pfull) 
+    export LEVS=$(${NCLEN} ${ATMGES} pfull)
     status=$?
 else
-    export LEVS=$($NEMSIOGET $ATMGES dimz | awk '{print $2}')
+    export LEVS=$(${NEMSIOGET} ${ATMGES} dimz | awk '{print $2}')
     status=$?
 fi
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
-if [ $DOHYBVAR = "YES" ]; then
-    export ATMGES_ENSMEAN="$COMIN_GES_ENS/${GPREFIX}atmf006.ensmean$GSUFFIX"
-    if [ ! -f $ATMGES_ENSMEAN ]; then
-        echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = $ATMGES_ENSMEAN"
+if [ ${DOHYBVAR} = "YES" ]; then
+    export ATMGES_ENSMEAN="${COMIN_GES_ENS}/${GPREFIX}atmf006.ensmean${GSUFFIX}"
+    if [ ! -f ${ATMGES_ENSMEAN} ]; then
+        echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = ${ATMGES_ENSMEAN}"
         exit 2
     fi
 fi
@@ -123,46 +118,46 @@ fi
 
 # Link observational data
 export PREPQC="${COMIN_OBS}/${OPREFIX}prepbufr"
-if [ ! -f $PREPQC ]; then
-    echo "WARNING: Global PREPBUFR FILE $PREPQC MISSING"
+if [ ! -f ${PREPQC} ]; then
+    echo "WARNING: Global PREPBUFR FILE ${PREPQC} MISSING"
 fi
 export TCVITL="${COMOUT}/${OPREFIX}syndata.tcvitals.tm00"
-if [[ $DONST = "YES" ]]; then
-   if [[ $MAKE_NSSTBUFR == "YES" ]]; then
+if [[ ${DONST} = "YES" ]]; then
+   if [[ ${MAKE_NSSTBUFR} == "YES" ]]; then
       export NSSTBF="${COMOUT}/${OPREFIX}nsstbufr"
    else
       export NSSTBF="${COMIN_OBS}/${OPREFIX}nsstbufr"
    fi
 fi
 
-if [[ $MAKE_ACFTBUFR == "YES" ]]; then
+if [[ ${MAKE_ACFTBUFR} == "YES" ]]; then
    export PREPQCPF="${COMOUT}/${OPREFIX}prepbufr.acft_profiles"
 else
    export PREPQCPF="${COMIN_OBS}/${OPREFIX}prepbufr.acft_profiles"
 fi
 
-# Copy fix file for obsproc
-if [ $RUN = "gfs" ]; then
-    mkdir -p $ROTDIR/fix
-    cp $FIXgsi/prepobs_errtable.global $ROTDIR/fix/
+# Copy fix file for obsproc  # TODO: Why is this necessary?
+if [ ${RUN} = "gfs" ]; then
+    mkdir -p ${ROTDIR}/fix
+    cp ${FIXgsi}/prepobs_errtable.global ${ROTDIR}/fix/
 fi
 
 
 ###############################################################
 # Run relevant script
 
-${ANALYSISSH:-$SCRgfs/exglobal_atmos_analysis.sh}
+${ANALYSISSH:-${SCRgfs}/exglobal_atmos_analysis.sh}
 status=$?
-[[ $status -ne 0 ]] && exit $status
+[[ ${status} -ne 0 ]] && exit ${status}
 
 
 ##############################################
 # Send Alerts
 ##############################################
-if [ $SENDDBN = YES -a $RUN = gdas ] ; then
-    $DBNROOT/bin/dbn_alert MODEL GDAS_MSC_abias $job $COMOUT/${APREFIX}abias
-    $DBNROOT/bin/dbn_alert MODEL GDAS_MSC_abias_pc $job $COMOUT/${APREFIX}abias_pc
-    $DBNROOT/bin/dbn_alert MODEL GDAS_MSC_abias_air $job $COMOUT/${APREFIX}abias_air
+if [ ${SENDDBN} = YES -a ${RUN} = gdas ] ; then
+    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias ${job} ${COMOUT}/${APREFIX}abias
+    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias_pc ${job} ${COMOUT}/${APREFIX}abias_pc
+    ${DBNROOT}/bin/dbn_alert MODEL GDAS_MSC_abias_air ${job} ${COMOUT}/${APREFIX}abias_air
 fi
 
 
@@ -173,14 +168,14 @@ fi
 ##############################################
 # Final processing
 ##############################################
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
+if [ -e "${pgmout}" ] ; then
+  cat ${pgmout}
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd $DATAROOT
+cd ${DATAROOT}
 [[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
 
 
