fixes after code scanning/shellcheck

diff --git a/jobs/JGEFS_WAVE_STAT b/jobs/JGEFS_WAVE_STAT
--- a/jobs/JGEFS_WAVE_STAT
+++ b/jobs/JGEFS_WAVE_STAT
@@ -43,13 +43,14 @@ export WAV_MOD_TAG=${RUN}wave${waveMEMB}
 export CFP_VERBOSE=1
 
 # Execute the Script
-${SCRgfs}/exgfs_wave_stat.sh
+"${SCRgfs}/exgfs_wave_stat.sh"
 
 ##########################################
-# Remove the Temporary working directory
-##########################################
-cd ${DATAROOT}
-[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
-
+## Remove the Temporary working directory
+###########################################
+cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
+if [[ "${KEEPDATA}" == "NO" ]]; then
+    rm -rf "${DATA}"
+fi
  
 exit 0
diff --git a/jobs/JGEFS_WAVE_STAT_PNT b/jobs/JGEFS_WAVE_STAT_PNT
--- a/jobs/JGEFS_WAVE_STAT_PNT
+++ b/jobs/JGEFS_WAVE_STAT_PNT
@@ -48,13 +48,16 @@ export wavempexec=${wavempexec:-"mpirun -n"}
 export wave_mpmd=${wave_mpmd:-"cfp"}
 
 # Execute the Script
-${SCRgfs}/exgfs_wave_stat_pnt.sh
+"${SCRgfs}/exgfs_wave_stat_pnt.sh"
 
 ##########################################
-# Remove the Temporary working directory
-##########################################
-cd ${DATAROOT}
-[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
+## Remove the Temporary working directory
+###########################################
+cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
+if [[ "${KEEPDATA}" == "NO" ]]; then
+    rm -rf "${DATA}"
+fi
+
 
  
 exit 0
