review modifications

diff --git a/jobs/JGLOBAL_PREP_OCEAN_OBS b/jobs/JGLOBAL_PREP_OCEAN_OBS
--- a/jobs/JGLOBAL_PREP_OCEAN_OBS
+++ b/jobs/JGLOBAL_PREP_OCEAN_OBS
@@ -7,8 +7,6 @@ source "${HOMEgfs}/ush/jjob_header.sh" -e "prepoceanobs" -c "base prepoceanobs"
 ##############################################
 # Set variables used in the script
 ##############################################
-# Ignore possible spelling error (nothing is misspelled)
-# shellcheck disable=SC2153
 
 ##############################################
 # Begin JOB SPECIFIC work
@@ -32,8 +30,9 @@ if [[ -e "${pgmout}" ]] ; then
 fi
 
 ##########################################
-# Do not remove the Temporary working directory (do this in POST)
+# Handle the temporary working directory 
 ##########################################
-cd "${DATAROOT}" || exit 1
+cd "${DATAROOT}" || (echo "FATAL ERROR: ${DATAROOT} does not exist. ABORT!"; exit 1)
+[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"
 
 exit 0
