Vlab issue #65376:  DA changes for GFSv16.  Fixes #65376.
Change-Id: Id7ea8df4b8f5b2b7961456c5c961c1ad712385a6

diff --git a/jobs/JGLOBAL_ENKF_ANALDIAG b/jobs/JGLOBAL_ENKF_ANALDIAG
--- a/jobs/JGLOBAL_ENKF_ANALDIAG
+++ b/jobs/JGLOBAL_ENKF_ANALDIAG
@@ -10,7 +10,7 @@ date
 # Source relevant config files
 #############################
 export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
-configs="base ecen"
+configs="base anal eobs ediag"
 config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
 for config in $configs; do
     . $config_path/config.$config
@@ -22,7 +22,7 @@ done
 ##########################################
 # Source machine runtime environment
 ##########################################
-. $HOMEgfs/env/${machine}.env ecen
+. $HOMEgfs/env/${machine}.env eobs
 status=$?
 [[ $status -ne 0 ]] && exit $status
 
@@ -72,21 +72,13 @@ gcyc=$(echo $GDATE | cut -c9-10)
 GDUMP=${GDUMP:-"gdas"}
 
 export CASE=$CASE_ENKF
+export CDUMP_OBS=${CDUMP_OBS:-$CDUMP}
 
-
-EUPD_CYC=$(echo ${EUPD_CYC:-"gdas"} | tr a-z A-Z)
-if [ $EUPD_CYC = "GFS" ]; then
-    CDUMP_ENKF="gfs"
-else
-    CDUMP_ENKF=$CDUMP
-fi
-
-export OPREFIX="${CDUMP}.t${cyc}z."
+export OPREFIX="${CDUMP_OBS}.t${cyc}z."
 export APREFIX="${CDUMP}.t${cyc}z."
-export APREFIX_ENKF="${CDUMP_ENKF}.t${cyc}z."
-export GPREFIX="${CDUMP}.t${gcyc}z."
-export GSUFFIX=${GSUFFIX:-$SUFFIX}
-export ASUFFIX=${ASUFFIX:-$SUFFIX}
+export GPREFIX="${GDUMP}.t${gcyc}z."
+export GSUFFIX="${GSUFFIX:-".ensmean${SUFFIX}"}"
+export ASUFFIX="${ASUFFIX:-"${SUFFIX}"}"
 
 if [ $RUN_ENVIR = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
     export COMIN_OBS=${COMIN_OBS:-$ROTDIR/$RUN.$PDY/$cyc}
@@ -96,12 +88,69 @@ else
     export COMIN_GES_OBS="$DMPDIR/$GDATE/$GDUMP"
 fi
 
-# COMIN, COMIN_ENS and COMIN_GES_ENS are used in exglobal script
+# COMIN_GES, COMIN_ANL COMIN_GES_ENS, and COMOUT  are used in exglobal script
 # TO DO: Map NCO's directory into these variables
-export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc"
-export COMIN_ENS="$ROTDIR/enkf$CDUMP_ENKF.$PDY/$cyc"
-export COMOUT_ENS="$ROTDIR/enkf$CDUMP.$PDY/$cyc"
-export COMIN_GES_ENS="$ROTDIR/enkf$CDUMP.$gPDY/$gcyc"
+COMIN_GES_CTL="$ROTDIR/gdas.$gPDY/$gcyc"
+export COMIN_ANL="$ROTDIR/$CDUMP.$PDY/$cyc"
+export COMIN_GES_ENS="$ROTDIR/enkfgdas.$gPDY/$gcyc"
+export COMIN_GES=$COMIN_GES_ENS
+export COMOUT="$ROTDIR/enkf$CDUMP.$PDY/$cyc"
+
+
+export ATMGES_ENSMEAN="$COMIN_GES_ENS/${GPREFIX}atmf006$GSUFFIX"
+if [ ! -f $ATMGES_ENSMEAN ]; then
+    echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = $ATMGES_ENSMEAN"
+    exit 1
+fi
+
+export LEVS=$($NCDUMP -h $ATMGES_ENSMEAN | grep -i "pfull" | head -1 | awk -F" = " '{print $2}' | awk -F" " '{print $1}') # get LEVS
+status=$?
+[[ $status -ne 0 ]] && exit $status
+
+# Link observational data
+export PREPQC="$COMIN_ANL/${OPREFIX}prepbufr"
+if [ ! -f $PREPQC ]; then
+    echo "WARNING: PREPBUFR FILE $PREPQC MISSING"
+    msg="WARNING : Global PREPBUFR file is missing"
+    postmsg "$jlogfile" "$msg"
+fi
+export PREPQCPF="$COMIN_ANL/${OPREFIX}prepbufr.acft_profiles"
+export TCVITL="$COMIN_ANL/${OPREFIX}syndata.tcvitals.tm00"
+[[ $DONST = "YES" ]] && export NSSTBF="$COMIN_ANL/${OPREFIX}nsstbufr"
+
+# Guess Bias correction coefficients related to control
+export GBIAS=${COMIN_GES_CTL}/${GPREFIX}abias
+export GBIASPC=${COMIN_GES_CTL}/${GPREFIX}abias_pc
+export GBIASAIR=${COMIN_GES_CTL}/${GPREFIX}abias_air
+export GRADSTAT=${COMIN_GES_CTL}/${GPREFIX}radstat
+
+# Bias correction coefficients related to ensemble mean
+export ABIAS="$COMOUT/${APREFIX}abias.ensmean"
+export ABIASPC="$COMOUT/${APREFIX}abias_pc.ensmean"
+export ABIASAIR="$COMOUT/${APREFIX}abias_air.ensmean"
+export ABIASe="$COMOUT/${APREFIX}abias_int.ensmean"
+
+# Diagnostics related to ensemble mean
+export GSISTAT="$COMOUT/${APREFIX}gsistat.ensmean"
+export CNVSTAT="$COMOUT/${APREFIX}cnvstat.ensmean"
+export OZNSTAT="$COMOUT/${APREFIX}oznstat.ensmean"
+export RADSTAT="$COMOUT/${APREFIX}radstat.ensmean"
+
+# Select observations based on ensemble mean
+export RUN_SELECT="YES"
+export USE_SELECT="NO"
+export SELECT_OBS="$COMOUT/${APREFIX}obsinput.ensmean"
+
+export DIAG_SUFFIX="_ensmean"
+export DIAG_COMPRESS="NO"
+
+# GSI namelist options specific to eobs
+export SETUP_INVOBS="passive_bc=.false.,$SETUP_INVOBS"
+
+# Ensure clean stat tarballs for ensemble mean
+for fstat in $CNVSTAT $OZNSTAT $RADSTAT; do
+    [[ -f $fstat ]] && rm -f $fstat
+done
 
 
 ###############################################################
@@ -112,9 +161,17 @@ postmsg "$jlogfile" "$msg"
 $LOGSCRIPT
 
 
-${ENKFRECENSH:-$SCRgsi/exglobal_enkf_recenter_fv3gfs.sh.ecf}
+${ANALDIAGSH:-$SCRgsi/exglobal_analdiag_fv3gfs.sh.ecf}
 status=$?
 [[ $status -ne 0 ]] && exit $status
+
+
+##############################################
+# Send Alerts
+##############################################
+if [ $SENDDBN = YES ] ; then
+   $DBNROOT/bin/dbn_alert MODEL ENKF1_MSC_gsistat $job $GSISTAT
+fi
 
 
 ##############################################
