Rename wave output and refactor some wave scripts
Wave products are renamed to be uniform with other components and
follow NCO implementation standards. This means all output is in
the format `${RUN}.wave.tCCz.product[.fHHH][.domain].suffix`.

Some wave scripts (init and gridded post) are refactored to make
them consistent with other parts of the workflow. All scripts for
both jobs now pass `shellcheck` without warnings.

The biggest changes in the refactor include beyond those necessary
for the file rename include:
- Using the `run_mpmd.sh` script
- Updated templates to use atparse instead of `sed`
- Removed redirection of output to logs that get deleted (#296)

One functional change is raw interpolated grids are no longer
copied to COM, only the resulting grib files. Need to confirm with
Jessica this is okay.

Refs #296
Refs #3270

diff --git a/jobs/JGLOBAL_WAVE_POST_SBS b/jobs/JGLOBAL_WAVE_POST_SBS
--- a/jobs/JGLOBAL_WAVE_POST_SBS
+++ b/jobs/JGLOBAL_WAVE_POST_SBS
@@ -32,30 +32,21 @@ if [[ -n "${wavepostGRD}" || -n "${waveinterpGRD}" ]]; then
 else
     echo "Both wavepostGRD and waveinterpGRD are empty. No grids to process."
 fi
-# Set wave model ID tag to include member number
-# if ensemble; waveMEMB var empty in deterministic
-# Set wave model ID tag to include member number
-# if ensemble; waveMEMB var empty in deterministic
-membTAG='p'
-if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
-export membTAG
-export WAV_MOD_TAG=${RUN}wave${waveMEMB}
 
 export CFP_VERBOSE=1
 
 # Execute the Script
-${SCRgfs}/exgfs_wave_post_gridded_sbs.sh
+"${SCRgfs}/exgfs_wave_post_gridded_sbs.sh"
 err=$?
-if [ ${err} -ne 0 ]; then
-  echo "FATAL ERROR: ex-script of GWES_POST failed!"
-  exit ${err}
+if [[ ${err} -ne 0 ]]; then
+  echo "FATAL ERROR: ex-script of gridded wave post failed!"
+  exit "${err}"
 fi
 
 ##########################################
 # Remove the Temporary working directory
 ##########################################
-cd ${DATAROOT}
-[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
-
+cd "${DATAROOT}" || true
+if [[ ${KEEPDATA} = "NO" ]]; then rm -rf "${DATA}"; fi
 
 exit 0
