Shell norms

diff --git a/jobs/JGLOBAL_ATM_CALC_ANALYSIS b/jobs/JGLOBAL_ATM_CALC_ANALYSIS
--- a/jobs/JGLOBAL_ATM_CALC_ANALYSIS
+++ b/jobs/JGLOBAL_ATM_CALC_ANALYSIS
@@ -47,7 +47,7 @@ fi
 # Remove the Temporary working directory
 ##############################################
 
-cd ${DATAROOT}
+cd "${DATAROOT}" || ( echo "FATAL ERROR: ${DATAROOT} does not exist, ABORT!"; exit 1 )
 if [[ ${KEEPDATA} = "NO" ]]; then
     rm -rf "${DATA}"
 fi
