modified jobs\JGLOBAL_WAVE_POST_SBS

diff --git a/jobs/JGLOBAL_WAVE_POST_SBS b/jobs/JGLOBAL_WAVE_POST_SBS
--- a/jobs/JGLOBAL_WAVE_POST_SBS
+++ b/jobs/JGLOBAL_WAVE_POST_SBS
@@ -19,14 +19,42 @@ for out_dir in "${COMOUT_WAVE_PREP}" "${COMOUT_WAVE_GRID}"; do
     if [[ ! -d "${out_dir}" ]]; then mkdir -p "${out_dir}"; fi
 done
 
-for grid in "0p25" "0p50" "1p00"; do
-    GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
-    COMOUT_WAVE_GRID_${grid}:COM_WAVE_GRID_RES_TMPL
-    COMOUT=COMOUT_WAVE_GRID_${grid}
-    if [[ ! -d "${COMOUT}" ]]; then
-        mkdir -m 775 -p "${COMOUT}"
-    fi
+for grdID in ${wavepostGRD} ${waveinterpGRD}; do
+    case ${grdID} in
+        glo_15mxt) GRDRES=0p25;;
+        reg025) GRDRES=0p25;;
+        glo_025) GRDRES=0p25;;
+        glo_100) GRDRES=1p00;;
+        glo_200) GRDRES=2p00;;
+        glo_500) GRDRES=5p00;;
+        glo_30mxt) GRDRES=0p50;;
+        glo_30m) GRDRES=0p50;;
+        at_10m) GRDRES=0p16;;
+        ep_10m) GRDRES=0p16 ;;
+        wc_10m) GRDRES=0p16;;
+        ak_10m) GRDRES=0p16;;
+        ant_9km) GRDRES=9km;;
+        glo_10m) GRDRES=0p16;;
+        gnh_10m) GRDRES=0p16;;
+        gsh_15m) GRDRES=0p25;;
+        glo_15m) GRDRES=0p25;;
+        ao_20m) GRDRES=0p33;;
+        so_20m) GRDRES=0p33;;
+        gwes_30m) GRDRES=0p50;;
+        *)
+        echo "FATAL ERROR: No grid specific wave config values exist for ${grdID}. Aborting."
+        exit 1;;
+    esac
 done
+
+
+GRID=${grdID} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
+    "COMOUT_WAVE_GRID_${grdID}:COM_WAVE_GRID_RES_TMPL"
+COMOUT=COMOUT_WAVE_GRID_${grdID}
+if [[ ! -d "${COMOUT}" ]]; then
+    mkdir -m 775 -p "${COMOUT}"
+fi
+
 
 # Set wave model ID tag to include member number
 # if ensemble; waveMEMB var empty in deterministic
