Add preamble, convert to bash, and remove env
This is the first in a wave of commits to improve and standardize the
scripts within global workflow. In this commit, all scripts run during
execution are converted to bash and a preamble is added to every script
that is not sourced by another script.

Every script executed during a forecast cycle is converted to bash. This
was mostly straightforward, though there were a couple Korne-shell
conventions (primarily using `typeset` to format strings) that had to be
replaced with bash-compatable alternatives like `printf`. This in turn
required a few modification to prevent zero-padded numbers from being
treated as octals (other may have been pre-existing bugs).

The preamble contains a number of feature to standardize code and
improve script flow and debugging.

	First, it uses two variables, `$STRICT` and `$TRACE` to control the
	behavior of `set`. When `$STRICT` is `"YES"`, error on undefined
	variables (`set -u`) and exit on non-zero return (`set -e`) are turned
	on. When `$TRACE` is `"YES"`, command trace (`set -x`) is turned on and
	a useful string is set to `$PS4` that gives the name and line number of
	the script. Both `$STRICT` and `$TRACE` default to `"YES"`. They also
	set up commands, `$ERR_EXIT_ON` and `$TRACE_ON`, that will restore the
	setting of each in the event a script needs to temporarily turn them
	off.

	Second, the preamble sets up primative timing of scripts using Posix
	`date`.

	Third, it echos the script is beginning and at what time.

	Finally, it also establishes a postamble function and sets it to run as
	a trap of EXIT. The postamble will use the end time to calculate the
	run time of the script, then print that the script has ended at what
	time, how long has elapsed, and the exit code. By setting this up as a
	trap instead of just calling it at the end of the script, it ensures
	the postamble is called even if the script exits early because there is
	an error.

	In response to this standardization, parts of scripts that performed
	these preamble functions (announcing start/end, `set -x`, etc) have
	been deleted. For some scripts where temporarily turning off `-x` or
	`-e` is needed, they now use `$ERR_EXIT_ON` and `$TRACE_ON` to return
	to the correct state afterwards, instead of blindly turning the setting
	back on.

	Additionally, some modifications were needed to comply with `set -eu`.
	Mostly taking care of undefined variables, but also a couple instances
	where a non-zero return code had to be dealt with.

If users wish to use their own preamble script instead, the default
script can be overriden by setting `$PREAMBLE_SCRIPT` before the run
begins.

Instance where scripts would print the full list of environment
variables have been removed. These can be spot added back in to debug as
necessary. Alternatively, a future PR will add them back in in a
standardized way.

`rstprod.sh` is added to the link list from gsi_monitor.fd, as it is
needed for the radmon scripts.

The placeholders for AWIPS and GEMPAK in the Hera and Orion environment
scripts were replaced with the correct definitions. There were also
other modifications to AWIPS and GEMPAK scripts to get it working for
development (AWIPS still isn't and will be fixed in the future).

GSI scripts that were brought in recently had all of their backticks
replaced with `$(  )` as was done with all other script previously.

Refs: #397

diff --git a/jobs/JGLOBAL_WAVE_POST_BNDPNT b/jobs/JGLOBAL_WAVE_POST_BNDPNT
--- a/jobs/JGLOBAL_WAVE_POST_BNDPNT
+++ b/jobs/JGLOBAL_WAVE_POST_BNDPNT
@@ -1,9 +1,11 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
-date
+PREAMBLE_SCRIPT="${PREAMBLE_SCRIPT:-$HOMEgfs/ush/preamble.sh}"
+if [ -f "${PREAMBLE_SCRIPT}" ]; then
+  source $PREAMBLE_SCRIPT
+fi
+
 export RUN_ENVIR=${RUN_ENVIR:-"nco"}
-export PS4=' $SECONDS + '
-set -x -e
 
 #############################
 # Source relevant config files
@@ -68,11 +70,8 @@ export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/$COMPONENT}
 
 mkdir -p $COMOUT/station
 
-env | sort
 
 # Set wave model ID tag to include member number 
-# if ensemble; waveMEMB var empty in deterministic
-# Set wave model ID tag to include member number
 # if ensemble; waveMEMB var empty in deterministic
 membTAG='p'
 if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
@@ -91,11 +90,9 @@ export DOBNDPNT_WAV='YES'  #not boundary points
 $HOMEgfs/scripts/exgfs_wave_post_pnt.sh
 err=$?
 if [ $err -ne 0 ]; then
-  msg="FATAL ERROR: ex-script of GWES_POST failed!"
-else
-  msg="$job completed normally!"
+  echo "FATAL ERROR: ex-script of GWES_POST failed!"
+  exit ${err}
 fi
-postmsg "$jlogfile" "$msg"
 
 ##########################################
 # Remove the Temporary working directory
@@ -103,5 +100,5 @@ postmsg "$jlogfile" "$msg"
 cd $DATAROOT
 [[ $KEEPDATA = "NO" ]] && rm -rf $DATA
 
-date
+
 exit 0
diff --git a/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL b/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
--- a/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
+++ b/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
@@ -1,9 +1,11 @@
-#!/bin/bash
+#! /usr/bin/env bash
 
-date
+PREAMBLE_SCRIPT="${PREAMBLE_SCRIPT:-$HOMEgfs/ush/preamble.sh}"
+if [ -f "${PREAMBLE_SCRIPT}" ]; then
+  source $PREAMBLE_SCRIPT
+fi
+
 export RUN_ENVIR=${RUN_ENVIR:-"nco"}
-export PS4=' $SECONDS + '
-set -x -e
 
 #############################
 # Source relevant config files
@@ -69,7 +71,6 @@ export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/$COMPONENT}
 
 mkdir -p $COMOUT/station
 
-env | sort
 
 # Set wave model ID tag to include member number
 # if ensemble; waveMEMB var empty in deterministic
@@ -92,11 +93,9 @@ export DOBNDPNT_WAV='YES'  #boundary points
 $HOMEgfs/scripts/exgfs_wave_post_pnt.sh
 err=$?
 if [ $err -ne 0 ]; then
-  msg="FATAL ERROR: ex-script of GFS_WAVE_POST_PNT failed!"
-else
-  msg="$job completed normally!"
+  echo "FATAL ERROR: ex-script of GFS_WAVE_POST_PNT failed!"
+  exit ${err}
 fi
-postmsg "$jlogfile" "$msg"
 
 ##########################################
 # Remove the Temporary working directory
@@ -104,5 +103,5 @@ postmsg "$jlogfile" "$msg"
 cd $DATAROOT
 [[ $KEEPDATA = "NO" ]] && rm -rf $DATA
 
-date
+
 exit 0
