suggestions R

diff --git a/jobs/JGLOBAL_ATMOS_CHGRES_GEN_CONTROL b/jobs/JGLOBAL_ATMOS_CHGRES_GEN_CONTROL
--- a/jobs/JGLOBAL_ATMOS_CHGRES_GEN_CONTROL
+++ b/jobs/JGLOBAL_ATMOS_CHGRES_GEN_CONTROL
@@ -13,12 +13,21 @@ MEMDIR="mem000" YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
 MEMDIR="mem000" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
     COMOUT_ATMOS_INPUT_MEM:COM_ATMOS_INPUT_TMPL
 ###############################################################
+# Ensure COMIN_ATMOS_INPUT_MEM exists, create if needed
+if [[ ! -d "${COMOUT_ATMOS_INPUT_MEM}" ]]; then
+  if ! mkdir -p "${COMOUT_ATMOS_INPUT_MEM}"; then
+    echo "ERROR: Failed to create directory ${COMOUT_ATMOS_INPUT_MEM}"
+    exit 1
+  fi
+fi
+###############################################################
 # Run relevant script
 ${CHGRESFCSTSH:-${SCRgfs}/exglobal_atmos_chgres_gen_control.sh} && true
 export err=$?
 if [[ ${err} -ne 0 ]]; then
     err_exit
 fi
+################################################################
 
 ##########################################
 # Remove the Temporary working directory
