Update boundary point, wave gempak jobs for file rename
Updates the boundary point j-jobs and the gempak scripts for the
wave file rename.

The gempak scripts are also refactored to meet style guidelines. As
part of this, the job is changed to run one forecast hour at a time,
with a rocoto metatask for development. Grouping is done for this
metatask as with other product metatasks to reduce the job count.
For dependency reasons, these settings must be the same as the wave
gridded post, so the max tasks and fhrs are read from that config
set in rocoto.

Like the regular point job, the boundary point j-jobs are not
refactored as the point job will be redone soon anyway. Only changes
necessary for the new filenames are made.

diff --git a/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL b/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
--- a/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
+++ b/jobs/JGLOBAL_WAVE_POST_BNDPNTBLL
@@ -14,32 +14,27 @@ export MP_PULSE=0
 
 # Set COM Paths and GETGES environment
 YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
-   COMIN_WAVE_PREP:COM_WAVE_PREP_TMPL \
-   COMIN_WAVE_HISTORY:COM_WAVE_HISTORY_TMPL \
-   COMOUT_WAVE_STATION:COM_WAVE_STATION_TMPL
+	COMIN_WAVE_PREP:COM_WAVE_PREP_TMPL \
+	COMIN_WAVE_HISTORY:COM_WAVE_HISTORY_TMPL \
+	COMOUT_WAVE_STATION:COM_WAVE_STATION_TMPL
 
 if [[ ! -d "${COMOUT_WAVE_STATION}" ]]; then mkdir -p "${COMOUT_WAVE_STATION}"; fi
 
-# Set wave model ID tag to include member number
-# if ensemble; waveMEMB var empty in deterministic
-membTAG='p'
-if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
-export membTAG
-export WAV_MOD_TAG=${RUN}wave${waveMEMB}
+export WAV_MOD_TAG=${RUN}.wave
 
 export CFP_VERBOSE=1
 
 export FHMAX_WAV_PNT=${FHMAX_WAV_IBP}
-export DOSPC_WAV='NO' # Spectral post
-export DOBLL_WAV='YES' # Bulletin post
-export DOBNDPNT_WAV='YES'  #boundary points
+export DOSPC_WAV='NO'     # Spectral post
+export DOBLL_WAV='YES'    # Bulletin post
+export DOBNDPNT_WAV='YES' #boundary points
 
 # Execute the Script
 ${SCRgfs}/exgfs_wave_post_pnt.sh
 err=$?
 if [ ${err} -ne 0 ]; then
-  echo "FATAL ERROR: ex-script of GFS_WAVE_POST_PNT failed!"
-  exit ${err}
+	echo "FATAL ERROR: ex-script of GFS_WAVE_POST_PNT failed!"
+	exit ${err}
 fi
 
 ##########################################
@@ -47,6 +42,5 @@ fi
 ##########################################
 cd ${DATAROOT}
 [[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}
-
 
 exit 0
