Add GEFS fcst job support
Makes the minor changes necessary to run GEFS fcst job only from pre-staged
ICs. Also many unnecessary DA settings are removed from the GEFS version of
`config.base`.

Resolves #826

diff --git a/jobs/JGLOBAL_FORECAST b/jobs/JGLOBAL_FORECAST
--- a/jobs/JGLOBAL_FORECAST
+++ b/jobs/JGLOBAL_FORECAST
@@ -17,15 +17,23 @@ rCDUMP=${CDUMP}
 [[ ${CDUMP} = "gfs" ]] && export rCDUMP="gdas"
 
 # Forecast length for GFS forecast
-if [ ${CDUMP} = "gfs" ]; then
+case ${CDUMP} in
+  gfs | gefs)
+    # shellcheck disable=SC2153
     export FHMAX=${FHMAX_GFS}
+    # shellcheck disable=SC2153
     export FHOUT=${FHOUT_GFS}
     export FHMAX_HF=${FHMAX_HF_GFS}
     export FHOUT_HF=${FHOUT_HF_GFS}
-else
+    ;;
+  gdas)
     export FHMAX_HF=0
     export FHOUT_HF=0
-fi
+    ;;
+  *)
+    echo "FATAL ERROR: Unknown CDUMP '${CDUMP}'"
+    exit 1
+esac
 
 
 # Ignore possible spelling error (nothing is misspelled)
