Do not fail on external command errors/undefined variables

diff --git a/jobs/JGLOBAL_ARCHIVE_TARS b/jobs/JGLOBAL_ARCHIVE_TARS
--- a/jobs/JGLOBAL_ARCHIVE_TARS
+++ b/jobs/JGLOBAL_ARCHIVE_TARS
@@ -74,11 +74,10 @@ fi
 # Run archive script
 ###############################################################
 
+set +eu
 ${GLOBALARCHIVESH:-${SCRgfs}/exglobal_archive_tars.py}
-err=$?
-if [[ ${err} -ne 0 ]]; then
-    exit "${err}"
-fi
+export err=$?; err_chk "FATAL ERROR: failed to archive the COM structure"
+set_strict
 
 ##############################################
 # End JOB SPECIFIC work
diff --git a/jobs/JGLOBAL_ENS_ARCHIVE_TARS b/jobs/JGLOBAL_ENS_ARCHIVE_TARS
--- a/jobs/JGLOBAL_ENS_ARCHIVE_TARS
+++ b/jobs/JGLOBAL_ENS_ARCHIVE_TARS
@@ -19,11 +19,11 @@ if [[ ! -d ${COMOUT_CONF} ]]; then mkdir -p "${COMOUT_CONF}"; fi
 # Run archive script
 ###############################################################
 
+# Calls an external bash command; do not fail on unassigned/error
+set +eu
 "${SCRgfs}/exgdas_enkf_earc_tars.py"
-err=$?
-if [[ ${err} -ne 0 ]]; then
-    exit "${err}"
-fi
+export err=$?; err_chk "FATAL ERROR Failed to archive the ensemble COM structure"
+set_strict
 
 ###############################################################
 
