updates for SFS products

diff --git a/dev/jobs/JGLOBAL_ATMOS_POST b/dev/jobs/JGLOBAL_ATMOS_POST
--- a/dev/jobs/JGLOBAL_ATMOS_POST
+++ b/dev/jobs/JGLOBAL_ATMOS_POST
@@ -1,10 +1,18 @@
 #! /usr/bin/env bash
-source "${HOMEglobal}/ush/jjob_header.sh" -e "atmos_post" -c "base atmos_post"
+set -x
 
-export DATA="${DATAROOT}/atmos_post_${ENSMEM}.${jobid}"
-mkdir -p ${DATA}
-# Create the directory to hold output from the model in stmp
-export DATAoutput="${DATA}/output"
+source "${HOMEglobal}/ush/jjob_header.sh" -e "atmos_post" -c "base atmos_post"
+source "${HOMEglobal}/ush/jjob_standard_vars.sh"
+source "${USHglobal}/jjob_shell_setup.sh"
+
+if ((10#${ENSMEM:-0} > 0)); then
+    export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
+else
+    export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
+fi
+
+# Create the directory to hold output for this job
+export DATAoutput="${DATAjob}/output"
 if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi
 
 # Construct COM variables from templates
@@ -24,10 +32,10 @@ atmos_6hrly_num=$(( FHMAX_GFS / 6 + 1 )) #expected total number of atmos master 
 echo "INFO: Found ${#atmos_6hrly_files[@]} of 6hrly atmos master files."
 
 if [[ "${#atmos_6hrly_files[@]}" -lt "${atmos_6hrly_num}" ]]; then 
-   echo "ERROR: Atmos master file count mismatch detected!"
-   echo " 6hrly atmos master files: ${#atmos_6hrly_files[@]} Found VS  ${atmos_6hrly_num} Expected "
-   echo " FATAL: The 6hrly atmos master files are incomplete. Atmos post job quits!"
-   exit 1
+    echo "ERROR: Atmos master file count mismatch detected!"
+    echo " 6hrly atmos master files: ${#atmos_6hrly_files[@]} Found VS  ${atmos_6hrly_num} Expected "
+    echo " FATAL: The 6hrly atmos master files are incomplete. Atmos post job quits!"
+    exit 1
 fi
 
 ##############################################
diff --git a/dev/jobs/JGLOBAL_ICE_POST b/dev/jobs/JGLOBAL_ICE_POST
--- a/dev/jobs/JGLOBAL_ICE_POST
+++ b/dev/jobs/JGLOBAL_ICE_POST
@@ -1,12 +1,14 @@
 #! /usr/bin/env bash
 source "${HOMEglobal}/ush/jjob_header.sh" -e "ice_post" -c "base ice_post"
-export DATA="${DATAROOT}/ocean_post_${ENSMEM}.${jobid}"
-mkdir -p ${DATA}
+source "${HOMEglobal}/ush/jjob_standard_vars.sh"
+source "${USHglobal}/jjob_shell_setup.sh"
+
 if ((10#${ENSMEM:-0} > 0)); then
     export DATAoutput="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}/output"
 else
     export DATAoutput="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}/output"
 fi
+if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi
 
 # Construct COM variables from templates
 YMD=${PDY} HH=${cyc} 
@@ -26,10 +28,10 @@ ice_24hrly_num=$(( FHMAX_GFS / 24 )) #expected total number of ice 24hr_avg hist
 echo "INFO: Found ${#ice_24hrly_files[@]} of ice 24hr_avg history files."
 
 if [[ "${#ice_24hrly_files[@]}" -lt "${ice_24hrly_num}" ]]; then
-   echo "ERROR: Ice history file count mismatch detected!"
-   echo "ice 24hr_avg history files: ${#ice_24hrly_files[@]} Found VS ${ice_24hrly_num} Expected"
-   echo "FATAL: The ice history files are incomplete. Ice post job quits!"
-   exit 1
+    echo "ERROR: Ice history file count mismatch detected!"
+    echo "ice 24hr_avg history files: ${#ice_24hrly_files[@]} Found VS ${ice_24hrly_num} Expected"
+    echo "FATAL: The ice history files are incomplete. Ice post job quits!"
+    exit 1
 fi
 
 ##############################################
diff --git a/dev/jobs/JGLOBAL_OCN_POST b/dev/jobs/JGLOBAL_OCN_POST
--- a/dev/jobs/JGLOBAL_OCN_POST
+++ b/dev/jobs/JGLOBAL_OCN_POST
@@ -1,14 +1,18 @@
 #! /usr/bin/env bash
 set -x
-source "${HOMEglobal}/ush/jjob_header.sh" -e "ocn_post" -c "base ocn_post"
 
-export DATA="${DATAROOT}/ocean_post_${ENSMEM}.${jobid}"
-mkdir -p ${DATA}
+source "${HOMEglobal}/ush/jjob_header.sh" -e "ocn_post" -c "base ocn_post"
+source "${HOMEglobal}/ush/jjob_standard_vars.sh"
+source "${USHglobal}/jjob_shell_setup.sh"
+
 if ((10#${ENSMEM:-0} > 0)); then
-    export DATAoutput="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}/output"
+    export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
 else
-    export DATAoutput="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}/output"
+    export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
 fi
+# Create the directory to hold output for this job
+export DATAoutput="${DATAjob}/output"
+if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi
 
 # Construct COM variables from templates
 YMD=${PDY} HH=${cyc} 
@@ -31,11 +35,11 @@ echo "INFO: Found ${#ocn_24hrly_files[@]} of ocean 24hr_avg history files."
 echo "INFO: Found ${#ocn_6hrly_files[@]} of ocean 6hr_avg history files."
 
 if [[ "${#ocn_24hrly_files[@]}" -lt "${ocn_24hrly_num}" ]] || [[ "${#ocn_6hrly_files[@]}" -lt "${ocn_6hrly_num}" ]]; then
-   echo "ERROR: File count mismatch detected!"
-   echo "Ocean 24hr_avg fistory files: ${#ocn_24hrly_files[@]} Found vs ${ocn_24hrly_num} Expected"
-   echo "Ocean 6hr_avg history files:  ${#ocn_6hrly_files[@]} Found vs ${ocn_6hrly_num} Expected"
-   echo "FATAL: The ocean history files are incomplete. Ocean post job quits!"
-   exit 1
+    echo "ERROR: File count mismatch detected!"
+    echo "Ocean 24hr_avg fistory files: ${#ocn_24hrly_files[@]} Found vs ${ocn_24hrly_num} Expected"
+    echo "Ocean 6hr_avg history files:  ${#ocn_6hrly_files[@]} Found vs ${ocn_6hrly_num} Expected"
+    echo "FATAL: The ocean history files are incomplete. Ocean post job quits!"
+    exit 1
 fi
 
 ##############################################
