updates for scripts to error out if there are missing files

diff --git a/dev/jobs/JGLOBAL_ATMOS_POST b/dev/jobs/JGLOBAL_ATMOS_POST
--- a/dev/jobs/JGLOBAL_ATMOS_POST
+++ b/dev/jobs/JGLOBAL_ATMOS_POST
@@ -21,6 +21,19 @@ if [[ ! -d "${COMOUT_ATMOS_GRIB}" ]]; then mkdir -p "${COMOUT_ATMOS_GRIB}"; fi
 # Define current cycle
 export current_cycle="${PDY}${cyc}"
 
+# Check if atmos 6hrly master files are complete for atmos post job
+shopt -s nullglob
+atmos_6hrly_files=( "${COMIN_ATMOS_MASTER}/sfs.t00z.master.f"*".grib2" )
+atmos_6hrly_num=$(( FHMAX_GFS / 6 + 1 )) #expected total number of atmos master files
+echo "INFO: Found ${#atmos_6hrly_files[@]} of 6hrly atmos master files."
+
+if [[ "${#atmos_6hrly_files[@]}" -lt "${atmos_6hrly_num}" ]]; then 
+   echo "ERROR: Atmos master file count mismatch detected!"
+   echo " 6hrly atmos master files: ${#atmos_6hrly_files[@]} Found VS  ${atmos_6hrly_num} Expected "
+   echo " FATAL: The 6hrly atmos master files are incomplete. Atmos post job quits!"
+   exit 1
+fi
+
 ##############################################
 # Begin JOB SPECIFIC work
 ##############################################
diff --git a/dev/jobs/JGLOBAL_ICE_POST b/dev/jobs/JGLOBAL_ICE_POST
--- a/dev/jobs/JGLOBAL_ICE_POST
+++ b/dev/jobs/JGLOBAL_ICE_POST
@@ -21,6 +21,19 @@ if [[ ! -d "${COMOUT_ICE_NETCDF}" ]]; then mkdir -p "${COMOUT_ICE_NETCDF}"; fi
 # Define current cycle
 export current_cycle="${PDY}${cyc}"
 
+# Check if ice 24hr_avg native files are complete for ice post job
+shopt -s nullglob
+ice_24hrly_files=( "${COMOUT_ICE_NETCDF}/native/${RUN}.t${cyc}z.native.f"*".nc" ) # ice 24hr_avg history files
+ice_24hrly_num=$(( FHMAX_GFS / 24 )) #expected total number of ice 24hr_avg history files
+echo "INFO: Found ${#ice_24hrly_files[@]} of ice 24hr_avg history files."
+
+if [[ "${#ice_24hrly_files[@]}" -lt "${ice_24hrly_num}" ]]; then
+   echo "ERROR: Ice history file count mismatch detected!"
+   echo "ice 24hr_avg history files: ${#ice_24hrly_files[@]} Found VS ${ice_24hrly_num} Expected"
+   echo "FATAL: The ice history files are incomplete. Ice post job quits!"
+   exit 1
+fi
+
 ##############################################
 # Begin JOB SPECIFIC work
 ##############################################
diff --git a/dev/jobs/JGLOBAL_OCN_POST b/dev/jobs/JGLOBAL_OCN_POST
--- a/dev/jobs/JGLOBAL_OCN_POST
+++ b/dev/jobs/JGLOBAL_OCN_POST
@@ -21,6 +21,23 @@ if [[ ! -d "${COMOUT_OCEAN_NETCDF}" ]]; then mkdir -p "${COMOUT_OCEAN_NETCDF}"; 
 # Define current cycle
 export current_cycle="${PDY}${cyc}"
 
+# Check if ocean 24hr_avg and 6hr_avg history files are complete for ocn post job
+shopt -s nullglob
+ocn_24hrly_files=( "${COMOUT_OCEAN_NETCDF}/${grid}/${RUN}.t${cyc}z.1p00.f"*".nc" ) # ocean 24hr_avg history files
+ocn_6hrly_files=( "${DATAoutput}/MOM6_OUTPUT/temp_"*".nc" ) # ocean (temp) 6hr_avg history files
+ocn_24hrly_num=$(( FHMAX_GFS / 24 )) #expected total number of ocean 24hr_avg files
+ocn_6hrly_num=$(( FHMAX_GFS / 6 )) #expected total number of ocean 6hr_avg files
+echo "INFO: Found ${#ocn_24hrly_files[@]} of ocean 24hr_avg history files."
+echo "INFO: Found ${#ocn_6hrly_files[@]} of ocean 6hr_avg history files."
+
+if [[ "${#ocn_24hrly_files[@]}" -lt "${ocn_24hrly_num}" ]] || [[ "${#ocn_6hrly_files[@]}" -lt "${ocn_6hrly_num}" ]]; then
+   echo "ERROR: File count mismatch detected!"
+   echo "Ocean 24hr_avg fistory files: ${#ocn_24hrly_files[@]} Found vs ${ocn_24hrly_num} Expected"
+   echo "Ocean 6hr_avg history files:  ${#ocn_6hrly_files[@]} Found vs ${ocn_6hrly_num} Expected"
+   echo "FATAL: The ocean history files are incomplete. Ocean post job quits!"
+   exit 1
+fi
+
 ##############################################
 # Begin JOB SPECIFIC work
 ##############################################
