(dev/gfs.v17) Fix Fit2Obs in the auxiliary workflow; run the auxiliary workflow in a separate location (#5226)
This fixes the `COMIN_OBS` construction in `JGDAS_FIT2OBS` when running
the auxiliary workflow (i.e. via `compath.py`).

This also makes some adjustments to the auxiliary workflow so that it
runs outside of `HOMEglobal`. This makes the installation and
maintenance easier.

diff --git a/dev/parm/config/gfs/config.arch_tars.j2 b/dev/parm/config/gfs/config.arch_tars.j2
--- a/dev/parm/config/gfs/config.arch_tars.j2
+++ b/dev/parm/config/gfs/config.arch_tars.j2
@@ -29,6 +29,9 @@ export ARCH_GAUSSIAN_FHINC=${FHOUT_GFS:-}
 
 # If we are running globus archiving, create tarballs in a temporary location
 if [[ "${ARCHCOM_TO}" == "globus_hpss" ]]; then
+    # Globus archiving is disabled for this pre-production branch
+    echo "FATAL ERROR: globus archiving is disabled."
+    exit 1
     export ATARDIR="${DATAROOT}/archive_rotdir/${RUN}"
     export ARCHCOM_TO="local"
 fi
