Update globalworkflow-ci.yaml
link was before build - fixed

diff --git a/.github/workflows/globalworkflow-ci.yaml b/.github/workflows/globalworkflow-ci.yaml
--- a/.github/workflows/globalworkflow-ci.yaml
+++ b/.github/workflows/globalworkflow-ci.yaml
@@ -55,15 +55,6 @@ jobs:
       uses: actions-ecosystem/action-add-labels@v1
       with:
         labels: "CI-Orion-Failed"
-
-    - name: Link artifacts
-      run: |
-        cd ${{ env.HOMEgfs }}/sorc
-        ./link_workflow.sh
-        if [ $? -ne 0 ]; then
-          echo "Linking artifacts failed"
-          exit 1
-        fi
     
     - name: Build components
       run: |
@@ -71,6 +62,15 @@ jobs:
         ./build_all.sh
         if [ $? -ne 0 ]; then
           echo "Build failed"
+          exit 1
+        fi
+        
+    - name: Link artifacts
+      run: |
+        cd ${{ env.HOMEgfs }}/sorc
+        ./link_workflow.sh
+        if [ $? -ne 0 ]; then
+          echo "Linking artifacts failed"
           exit 1
         fi
 
