updated messaging details for building status

diff --git a/.github/workflows/globalworkflow-ci.yaml b/.github/workflows/globalworkflow-ci.yaml
--- a/.github/workflows/globalworkflow-ci.yaml
+++ b/.github/workflows/globalworkflow-ci.yaml
@@ -30,9 +30,7 @@ jobs:
         HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
         REPO_URL: ${{ github.server_url }}/${{ github.repository }}
       run: |
-        cd $HOMEgfs/sorc
-        ./checkout.sh  # Options e.g. -g -u can be added late
-        cd $HOMEgfs
+        cd ${HOMEgfs}
         {
           echo "Automated global-workflow Testing Results:"
           echo '```'
@@ -40,31 +38,60 @@ jobs:
           echo "Start: $(date) on $(hostname)" || true
           echo "---------------------------------------------------"
         }  >> global-workflow.log
-        gh pr comment ${{ github.event.pull_request.number }} --repo $REPO_URL --body "$(cat global-workflow.log)"
+        cd $HOMEgfs/sorc
+        ./checkout.sh  # Options e.g. -g -u can be added late
+        if [ $? -ne 0 ]; then
+          {
+            echo "Checkout:                      *FAILED*"
+            echo "Checkout: Failed at $(date)" || true
+            echo "Checkout: see output at ${PWD}/log.checkout"
+          } >> ${HOMEgfs}/global-workflow.log
+          exit 1
+        else
+         {
+           echo "Checkout:                      *SUCCESS*"
+           echo "Checkout: Completed at $(date)" || true
+         } >> ${HOMEgfs}/global-workflow.log
+        fi
+        gh pr comment ${{ github.event.pull_request.number }} --repo $REPO_URL --body-file ${HOMEgfs}/global-workflow.log
 
     - name: Build
       env:
-        HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
         REPO_URL: ${{ github.server_url }}/${{ github.repository }}
         MACHINE_ID: orion
         pr: ${{ github.event.pull_request.number }}
       run: |
         gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Ready" --add-label "CI-${MACHINE_ID^}-Building"
+
         cd ${HOMEgfs}/sorc
         ./build_all.sh
-        if [ $? -ne 0 ]; then
-          gh pr comment ${pr} --repo ${REPO_URL} --body "Automated global-workflow Testing Results: \n\n Build Failed"
-          gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Building" --add-label "CI-${MACHINE_ID^}-Failed"
-          exit 1
-        else
-          gh pr comment ${pr} --repo $REPO_URL --body "Automated global-workflow Testing Results: \n\n Build Passed"
-          gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Building" --add-label "CI-${MACHINE_ID^}-Running"
-        fi 
 
     - name: Link
+        HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
+        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
+        MACHINE_ID: orion
+        pr: ${{ github.event.pull_request.number }}
       run: |
         cd ${{ github.event.pull_request.number }}/sorc
         ./link_workflow.sh
+
+        if [ $? -ne 0 ]; then
+          {
+            echo "Build:                         *FAILED*"
+            echo "Build: Failed at $(date)" || true
+            echo "Build: see output at ${PWD}/log.build"
+          } >> ${HOMEgfs}/global-workflow.log
+          gh pr comment ${pr} --repo ${REPO_URL} --body-file global-workflow.log 
+          gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Building" --add-label "CI-${MACHINE_ID^}-Failed"
+          exit 1
+        else
+          {
+            echo "Build:                         *SUCCESS*"
+            echo "Build: Completed at $(date)" || true
+          } >> ${HOMEgfs}/global-workflow.log
+          gh pr comment ${pr} --repo $REPO_URL --body-file ${HOMEgfs}/global-workflow.log
+          gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Building" --add-label "CI-${MACHINE_ID^}-Running"
+        fi 
         
   create-experiments:
       needs: clone-build
